/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LoginCallbackRouteImport } from './routes/login.callback'
import { Route as AuthenticatedVpcsIndexRouteImport } from './routes/_authenticated/vpcs/index'
import { Route as AuthenticatedVolumesIndexRouteImport } from './routes/_authenticated/volumes/index'
import { Route as AuthenticatedVmInstancesIndexRouteImport } from './routes/_authenticated/vm-instances/index'
import { Route as AuthenticatedVectorStoresIndexRouteImport } from './routes/_authenticated/vector-stores/index'
import { Route as AuthenticatedSubnetsIndexRouteImport } from './routes/_authenticated/subnets/index'
import { Route as AuthenticatedSecurityGroupsIndexRouteImport } from './routes/_authenticated/security-groups/index'
import { Route as AuthenticatedSandboxInstancesIndexRouteImport } from './routes/_authenticated/sandbox-instances/index'
import { Route as AuthenticatedRoutesIndexRouteImport } from './routes/_authenticated/routes/index'
import { Route as AuthenticatedRegistryIndexRouteImport } from './routes/_authenticated/registry/index'
import { Route as AuthenticatedOverviewComputeIndexRouteImport } from './routes/_authenticated/overview-compute/index'
import { Route as AuthenticatedObjectsIndexRouteImport } from './routes/_authenticated/objects/index'
import { Route as AuthenticatedModelsIndexRouteImport } from './routes/_authenticated/models/index'
import { Route as AuthenticatedLoadBalancersIndexRouteImport } from './routes/_authenticated/load-balancers/index'
import { Route as AuthenticatedKbIndexRouteImport } from './routes/_authenticated/kb/index'
import { Route as AuthenticatedK8sClustersIndexRouteImport } from './routes/_authenticated/k8s-clusters/index'
import { Route as AuthenticatedInferenceIndexRouteImport } from './routes/_authenticated/inference/index'
import { Route as AuthenticatedImagesIndexRouteImport } from './routes/_authenticated/images/index'
import { Route as AuthenticatedGpuInventoryIndexRouteImport } from './routes/_authenticated/gpu-inventory/index'
import { Route as AuthenticatedGpuInstancesIndexRouteImport } from './routes/_authenticated/gpu-instances/index'
import { Route as AuthenticatedFilesystemsIndexRouteImport } from './routes/_authenticated/filesystems/index'
import { Route as AuthenticatedContainerInstancesIndexRouteImport } from './routes/_authenticated/container-instances/index'
import { Route as AuthenticatedVpcsVpcIdRouteImport } from './routes/_authenticated/vpcs/$vpcId'
import { Route as AuthenticatedVolumesVolumeIdRouteImport } from './routes/_authenticated/volumes/$volumeId'
import { Route as AuthenticatedVmInstancesInstanceIdRouteImport } from './routes/_authenticated/vm-instances/$instanceId'
import { Route as AuthenticatedVectorStoresVectorStoreIdRouteImport } from './routes/_authenticated/vector-stores/$vectorStoreId'
import { Route as AuthenticatedSubnetsSubnetIdRouteImport } from './routes/_authenticated/subnets/$subnetId'
import { Route as AuthenticatedSecurityGroupsSecurityGroupIdRouteImport } from './routes/_authenticated/security-groups/$securityGroupId'
import { Route as AuthenticatedSandboxInstancesInstanceIdRouteImport } from './routes/_authenticated/sandbox-instances/$instanceId'
import { Route as AuthenticatedRoutesRouteIdRouteImport } from './routes/_authenticated/routes/$routeId'
import { Route as AuthenticatedObjectsBucketIdRouteImport } from './routes/_authenticated/objects/$bucketId'
import { Route as AuthenticatedModelsModelIdRouteImport } from './routes/_authenticated/models/$modelId'
import { Route as AuthenticatedLoadBalancersLoadBalancerIdRouteImport } from './routes/_authenticated/load-balancers/$loadBalancerId'
import { Route as AuthenticatedKbKbIdRouteImport } from './routes/_authenticated/kb/$kbId'
import { Route as AuthenticatedK8sClustersClusterIdRouteImport } from './routes/_authenticated/k8s-clusters/$clusterId'
import { Route as AuthenticatedInferenceServiceIdRouteImport } from './routes/_authenticated/inference/$serviceId'
import { Route as AuthenticatedGpuInstancesInstanceIdRouteImport } from './routes/_authenticated/gpu-instances/$instanceId'
import { Route as AuthenticatedFilesystemsFilesystemIdRouteImport } from './routes/_authenticated/filesystems/$filesystemId'
import { Route as AuthenticatedContainerInstancesInstanceIdRouteImport } from './routes/_authenticated/container-instances/$instanceId'
import { Route as AuthenticatedObjectsBucketIdIndexRouteImport } from './routes/_authenticated/objects/$bucketId/index'
import { Route as AuthenticatedObjectsBucketIdObjectIdRouteImport } from './routes/_authenticated/objects/$bucketId/$objectId'
import { Route as AuthenticatedVmInstancesInstanceIdVolumesVolumeIdRouteImport } from './routes/_authenticated/vm-instances/$instanceId/volumes/$volumeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedVpcsIndexRoute = AuthenticatedVpcsIndexRouteImport.update({
  id: '/vpcs/',
  path: '/vpcs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVolumesIndexRoute =
  AuthenticatedVolumesIndexRouteImport.update({
    id: '/volumes/',
    path: '/volumes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVmInstancesIndexRoute =
  AuthenticatedVmInstancesIndexRouteImport.update({
    id: '/vm-instances/',
    path: '/vm-instances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVectorStoresIndexRoute =
  AuthenticatedVectorStoresIndexRouteImport.update({
    id: '/vector-stores/',
    path: '/vector-stores/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubnetsIndexRoute =
  AuthenticatedSubnetsIndexRouteImport.update({
    id: '/subnets/',
    path: '/subnets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSecurityGroupsIndexRoute =
  AuthenticatedSecurityGroupsIndexRouteImport.update({
    id: '/security-groups/',
    path: '/security-groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxInstancesIndexRoute =
  AuthenticatedSandboxInstancesIndexRouteImport.update({
    id: '/sandbox-instances/',
    path: '/sandbox-instances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoutesIndexRoute =
  AuthenticatedRoutesIndexRouteImport.update({
    id: '/routes/',
    path: '/routes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistryIndexRoute =
  AuthenticatedRegistryIndexRouteImport.update({
    id: '/registry/',
    path: '/registry/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOverviewComputeIndexRoute =
  AuthenticatedOverviewComputeIndexRouteImport.update({
    id: '/overview-compute/',
    path: '/overview-compute/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObjectsIndexRoute =
  AuthenticatedObjectsIndexRouteImport.update({
    id: '/objects/',
    path: '/objects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModelsIndexRoute =
  AuthenticatedModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoadBalancersIndexRoute =
  AuthenticatedLoadBalancersIndexRouteImport.update({
    id: '/load-balancers/',
    path: '/load-balancers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKbIndexRoute = AuthenticatedKbIndexRouteImport.update({
  id: '/kb/',
  path: '/kb/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedK8sClustersIndexRoute =
  AuthenticatedK8sClustersIndexRouteImport.update({
    id: '/k8s-clusters/',
    path: '/k8s-clusters/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInferenceIndexRoute =
  AuthenticatedInferenceIndexRouteImport.update({
    id: '/inference/',
    path: '/inference/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImagesIndexRoute =
  AuthenticatedImagesIndexRouteImport.update({
    id: '/images/',
    path: '/images/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGpuInventoryIndexRoute =
  AuthenticatedGpuInventoryIndexRouteImport.update({
    id: '/gpu-inventory/',
    path: '/gpu-inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGpuInstancesIndexRoute =
  AuthenticatedGpuInstancesIndexRouteImport.update({
    id: '/gpu-instances/',
    path: '/gpu-instances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilesystemsIndexRoute =
  AuthenticatedFilesystemsIndexRouteImport.update({
    id: '/filesystems/',
    path: '/filesystems/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContainerInstancesIndexRoute =
  AuthenticatedContainerInstancesIndexRouteImport.update({
    id: '/container-instances/',
    path: '/container-instances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVpcsVpcIdRoute = AuthenticatedVpcsVpcIdRouteImport.update({
  id: '/vpcs/$vpcId',
  path: '/vpcs/$vpcId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVolumesVolumeIdRoute =
  AuthenticatedVolumesVolumeIdRouteImport.update({
    id: '/volumes/$volumeId',
    path: '/volumes/$volumeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVmInstancesInstanceIdRoute =
  AuthenticatedVmInstancesInstanceIdRouteImport.update({
    id: '/vm-instances/$instanceId',
    path: '/vm-instances/$instanceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVectorStoresVectorStoreIdRoute =
  AuthenticatedVectorStoresVectorStoreIdRouteImport.update({
    id: '/vector-stores/$vectorStoreId',
    path: '/vector-stores/$vectorStoreId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubnetsSubnetIdRoute =
  AuthenticatedSubnetsSubnetIdRouteImport.update({
    id: '/subnets/$subnetId',
    path: '/subnets/$subnetId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSecurityGroupsSecurityGroupIdRoute =
  AuthenticatedSecurityGroupsSecurityGroupIdRouteImport.update({
    id: '/security-groups/$securityGroupId',
    path: '/security-groups/$securityGroupId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxInstancesInstanceIdRoute =
  AuthenticatedSandboxInstancesInstanceIdRouteImport.update({
    id: '/sandbox-instances/$instanceId',
    path: '/sandbox-instances/$instanceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoutesRouteIdRoute =
  AuthenticatedRoutesRouteIdRouteImport.update({
    id: '/routes/$routeId',
    path: '/routes/$routeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObjectsBucketIdRoute =
  AuthenticatedObjectsBucketIdRouteImport.update({
    id: '/objects/$bucketId',
    path: '/objects/$bucketId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModelsModelIdRoute =
  AuthenticatedModelsModelIdRouteImport.update({
    id: '/models/$modelId',
    path: '/models/$modelId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoadBalancersLoadBalancerIdRoute =
  AuthenticatedLoadBalancersLoadBalancerIdRouteImport.update({
    id: '/load-balancers/$loadBalancerId',
    path: '/load-balancers/$loadBalancerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKbKbIdRoute = AuthenticatedKbKbIdRouteImport.update({
  id: '/kb/$kbId',
  path: '/kb/$kbId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedK8sClustersClusterIdRoute =
  AuthenticatedK8sClustersClusterIdRouteImport.update({
    id: '/k8s-clusters/$clusterId',
    path: '/k8s-clusters/$clusterId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInferenceServiceIdRoute =
  AuthenticatedInferenceServiceIdRouteImport.update({
    id: '/inference/$serviceId',
    path: '/inference/$serviceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGpuInstancesInstanceIdRoute =
  AuthenticatedGpuInstancesInstanceIdRouteImport.update({
    id: '/gpu-instances/$instanceId',
    path: '/gpu-instances/$instanceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilesystemsFilesystemIdRoute =
  AuthenticatedFilesystemsFilesystemIdRouteImport.update({
    id: '/filesystems/$filesystemId',
    path: '/filesystems/$filesystemId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContainerInstancesInstanceIdRoute =
  AuthenticatedContainerInstancesInstanceIdRouteImport.update({
    id: '/container-instances/$instanceId',
    path: '/container-instances/$instanceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObjectsBucketIdIndexRoute =
  AuthenticatedObjectsBucketIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedObjectsBucketIdRoute,
  } as any)
const AuthenticatedObjectsBucketIdObjectIdRoute =
  AuthenticatedObjectsBucketIdObjectIdRouteImport.update({
    id: '/$objectId',
    path: '/$objectId',
    getParentRoute: () => AuthenticatedObjectsBucketIdRoute,
  } as any)
const AuthenticatedVmInstancesInstanceIdVolumesVolumeIdRoute =
  AuthenticatedVmInstancesInstanceIdVolumesVolumeIdRouteImport.update({
    id: '/volumes/$volumeId',
    path: '/volumes/$volumeId',
    getParentRoute: () => AuthenticatedVmInstancesInstanceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteWithChildren
  '/login/callback': typeof LoginCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/container-instances/$instanceId': typeof AuthenticatedContainerInstancesInstanceIdRoute
  '/filesystems/$filesystemId': typeof AuthenticatedFilesystemsFilesystemIdRoute
  '/gpu-instances/$instanceId': typeof AuthenticatedGpuInstancesInstanceIdRoute
  '/inference/$serviceId': typeof AuthenticatedInferenceServiceIdRoute
  '/k8s-clusters/$clusterId': typeof AuthenticatedK8sClustersClusterIdRoute
  '/kb/$kbId': typeof AuthenticatedKbKbIdRoute
  '/load-balancers/$loadBalancerId': typeof AuthenticatedLoadBalancersLoadBalancerIdRoute
  '/models/$modelId': typeof AuthenticatedModelsModelIdRoute
  '/objects/$bucketId': typeof AuthenticatedObjectsBucketIdRouteWithChildren
  '/routes/$routeId': typeof AuthenticatedRoutesRouteIdRoute
  '/sandbox-instances/$instanceId': typeof AuthenticatedSandboxInstancesInstanceIdRoute
  '/security-groups/$securityGroupId': typeof AuthenticatedSecurityGroupsSecurityGroupIdRoute
  '/subnets/$subnetId': typeof AuthenticatedSubnetsSubnetIdRoute
  '/vector-stores/$vectorStoreId': typeof AuthenticatedVectorStoresVectorStoreIdRoute
  '/vm-instances/$instanceId': typeof AuthenticatedVmInstancesInstanceIdRouteWithChildren
  '/volumes/$volumeId': typeof AuthenticatedVolumesVolumeIdRoute
  '/vpcs/$vpcId': typeof AuthenticatedVpcsVpcIdRoute
  '/container-instances': typeof AuthenticatedContainerInstancesIndexRoute
  '/filesystems': typeof AuthenticatedFilesystemsIndexRoute
  '/gpu-instances': typeof AuthenticatedGpuInstancesIndexRoute
  '/gpu-inventory': typeof AuthenticatedGpuInventoryIndexRoute
  '/images': typeof AuthenticatedImagesIndexRoute
  '/inference': typeof AuthenticatedInferenceIndexRoute
  '/k8s-clusters': typeof AuthenticatedK8sClustersIndexRoute
  '/kb': typeof AuthenticatedKbIndexRoute
  '/load-balancers': typeof AuthenticatedLoadBalancersIndexRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/objects': typeof AuthenticatedObjectsIndexRoute
  '/overview-compute': typeof AuthenticatedOverviewComputeIndexRoute
  '/registry': typeof AuthenticatedRegistryIndexRoute
  '/routes': typeof AuthenticatedRoutesIndexRoute
  '/sandbox-instances': typeof AuthenticatedSandboxInstancesIndexRoute
  '/security-groups': typeof AuthenticatedSecurityGroupsIndexRoute
  '/subnets': typeof AuthenticatedSubnetsIndexRoute
  '/vector-stores': typeof AuthenticatedVectorStoresIndexRoute
  '/vm-instances': typeof AuthenticatedVmInstancesIndexRoute
  '/volumes': typeof AuthenticatedVolumesIndexRoute
  '/vpcs': typeof AuthenticatedVpcsIndexRoute
  '/objects/$bucketId/$objectId': typeof AuthenticatedObjectsBucketIdObjectIdRoute
  '/objects/$bucketId/': typeof AuthenticatedObjectsBucketIdIndexRoute
  '/vm-instances/$instanceId/volumes/$volumeId': typeof AuthenticatedVmInstancesInstanceIdVolumesVolumeIdRoute
}
export interface FileRoutesByTo {
  '/login/callback': typeof LoginCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/container-instances/$instanceId': typeof AuthenticatedContainerInstancesInstanceIdRoute
  '/filesystems/$filesystemId': typeof AuthenticatedFilesystemsFilesystemIdRoute
  '/gpu-instances/$instanceId': typeof AuthenticatedGpuInstancesInstanceIdRoute
  '/inference/$serviceId': typeof AuthenticatedInferenceServiceIdRoute
  '/k8s-clusters/$clusterId': typeof AuthenticatedK8sClustersClusterIdRoute
  '/kb/$kbId': typeof AuthenticatedKbKbIdRoute
  '/load-balancers/$loadBalancerId': typeof AuthenticatedLoadBalancersLoadBalancerIdRoute
  '/models/$modelId': typeof AuthenticatedModelsModelIdRoute
  '/routes/$routeId': typeof AuthenticatedRoutesRouteIdRoute
  '/sandbox-instances/$instanceId': typeof AuthenticatedSandboxInstancesInstanceIdRoute
  '/security-groups/$securityGroupId': typeof AuthenticatedSecurityGroupsSecurityGroupIdRoute
  '/subnets/$subnetId': typeof AuthenticatedSubnetsSubnetIdRoute
  '/vector-stores/$vectorStoreId': typeof AuthenticatedVectorStoresVectorStoreIdRoute
  '/vm-instances/$instanceId': typeof AuthenticatedVmInstancesInstanceIdRouteWithChildren
  '/volumes/$volumeId': typeof AuthenticatedVolumesVolumeIdRoute
  '/vpcs/$vpcId': typeof AuthenticatedVpcsVpcIdRoute
  '/container-instances': typeof AuthenticatedContainerInstancesIndexRoute
  '/filesystems': typeof AuthenticatedFilesystemsIndexRoute
  '/gpu-instances': typeof AuthenticatedGpuInstancesIndexRoute
  '/gpu-inventory': typeof AuthenticatedGpuInventoryIndexRoute
  '/images': typeof AuthenticatedImagesIndexRoute
  '/inference': typeof AuthenticatedInferenceIndexRoute
  '/k8s-clusters': typeof AuthenticatedK8sClustersIndexRoute
  '/kb': typeof AuthenticatedKbIndexRoute
  '/load-balancers': typeof AuthenticatedLoadBalancersIndexRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/objects': typeof AuthenticatedObjectsIndexRoute
  '/overview-compute': typeof AuthenticatedOverviewComputeIndexRoute
  '/registry': typeof AuthenticatedRegistryIndexRoute
  '/routes': typeof AuthenticatedRoutesIndexRoute
  '/sandbox-instances': typeof AuthenticatedSandboxInstancesIndexRoute
  '/security-groups': typeof AuthenticatedSecurityGroupsIndexRoute
  '/subnets': typeof AuthenticatedSubnetsIndexRoute
  '/vector-stores': typeof AuthenticatedVectorStoresIndexRoute
  '/vm-instances': typeof AuthenticatedVmInstancesIndexRoute
  '/volumes': typeof AuthenticatedVolumesIndexRoute
  '/vpcs': typeof AuthenticatedVpcsIndexRoute
  '/objects/$bucketId/$objectId': typeof AuthenticatedObjectsBucketIdObjectIdRoute
  '/objects/$bucketId': typeof AuthenticatedObjectsBucketIdIndexRoute
  '/vm-instances/$instanceId/volumes/$volumeId': typeof AuthenticatedVmInstancesInstanceIdVolumesVolumeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/login/callback': typeof LoginCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/container-instances/$instanceId': typeof AuthenticatedContainerInstancesInstanceIdRoute
  '/_authenticated/filesystems/$filesystemId': typeof AuthenticatedFilesystemsFilesystemIdRoute
  '/_authenticated/gpu-instances/$instanceId': typeof AuthenticatedGpuInstancesInstanceIdRoute
  '/_authenticated/inference/$serviceId': typeof AuthenticatedInferenceServiceIdRoute
  '/_authenticated/k8s-clusters/$clusterId': typeof AuthenticatedK8sClustersClusterIdRoute
  '/_authenticated/kb/$kbId': typeof AuthenticatedKbKbIdRoute
  '/_authenticated/load-balancers/$loadBalancerId': typeof AuthenticatedLoadBalancersLoadBalancerIdRoute
  '/_authenticated/models/$modelId': typeof AuthenticatedModelsModelIdRoute
  '/_authenticated/objects/$bucketId': typeof AuthenticatedObjectsBucketIdRouteWithChildren
  '/_authenticated/routes/$routeId': typeof AuthenticatedRoutesRouteIdRoute
  '/_authenticated/sandbox-instances/$instanceId': typeof AuthenticatedSandboxInstancesInstanceIdRoute
  '/_authenticated/security-groups/$securityGroupId': typeof AuthenticatedSecurityGroupsSecurityGroupIdRoute
  '/_authenticated/subnets/$subnetId': typeof AuthenticatedSubnetsSubnetIdRoute
  '/_authenticated/vector-stores/$vectorStoreId': typeof AuthenticatedVectorStoresVectorStoreIdRoute
  '/_authenticated/vm-instances/$instanceId': typeof AuthenticatedVmInstancesInstanceIdRouteWithChildren
  '/_authenticated/volumes/$volumeId': typeof AuthenticatedVolumesVolumeIdRoute
  '/_authenticated/vpcs/$vpcId': typeof AuthenticatedVpcsVpcIdRoute
  '/_authenticated/container-instances/': typeof AuthenticatedContainerInstancesIndexRoute
  '/_authenticated/filesystems/': typeof AuthenticatedFilesystemsIndexRoute
  '/_authenticated/gpu-instances/': typeof AuthenticatedGpuInstancesIndexRoute
  '/_authenticated/gpu-inventory/': typeof AuthenticatedGpuInventoryIndexRoute
  '/_authenticated/images/': typeof AuthenticatedImagesIndexRoute
  '/_authenticated/inference/': typeof AuthenticatedInferenceIndexRoute
  '/_authenticated/k8s-clusters/': typeof AuthenticatedK8sClustersIndexRoute
  '/_authenticated/kb/': typeof AuthenticatedKbIndexRoute
  '/_authenticated/load-balancers/': typeof AuthenticatedLoadBalancersIndexRoute
  '/_authenticated/models/': typeof AuthenticatedModelsIndexRoute
  '/_authenticated/objects/': typeof AuthenticatedObjectsIndexRoute
  '/_authenticated/overview-compute/': typeof AuthenticatedOverviewComputeIndexRoute
  '/_authenticated/registry/': typeof AuthenticatedRegistryIndexRoute
  '/_authenticated/routes/': typeof AuthenticatedRoutesIndexRoute
  '/_authenticated/sandbox-instances/': typeof AuthenticatedSandboxInstancesIndexRoute
  '/_authenticated/security-groups/': typeof AuthenticatedSecurityGroupsIndexRoute
  '/_authenticated/subnets/': typeof AuthenticatedSubnetsIndexRoute
  '/_authenticated/vector-stores/': typeof AuthenticatedVectorStoresIndexRoute
  '/_authenticated/vm-instances/': typeof AuthenticatedVmInstancesIndexRoute
  '/_authenticated/volumes/': typeof AuthenticatedVolumesIndexRoute
  '/_authenticated/vpcs/': typeof AuthenticatedVpcsIndexRoute
  '/_authenticated/objects/$bucketId/$objectId': typeof AuthenticatedObjectsBucketIdObjectIdRoute
  '/_authenticated/objects/$bucketId/': typeof AuthenticatedObjectsBucketIdIndexRoute
  '/_authenticated/vm-instances/$instanceId/volumes/$volumeId': typeof AuthenticatedVmInstancesInstanceIdVolumesVolumeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/login/callback'
    | '/'
    | '/login/'
    | '/container-instances/$instanceId'
    | '/filesystems/$filesystemId'
    | '/gpu-instances/$instanceId'
    | '/inference/$serviceId'
    | '/k8s-clusters/$clusterId'
    | '/kb/$kbId'
    | '/load-balancers/$loadBalancerId'
    | '/models/$modelId'
    | '/objects/$bucketId'
    | '/routes/$routeId'
    | '/sandbox-instances/$instanceId'
    | '/security-groups/$securityGroupId'
    | '/subnets/$subnetId'
    | '/vector-stores/$vectorStoreId'
    | '/vm-instances/$instanceId'
    | '/volumes/$volumeId'
    | '/vpcs/$vpcId'
    | '/container-instances'
    | '/filesystems'
    | '/gpu-instances'
    | '/gpu-inventory'
    | '/images'
    | '/inference'
    | '/k8s-clusters'
    | '/kb'
    | '/load-balancers'
    | '/models'
    | '/objects'
    | '/overview-compute'
    | '/registry'
    | '/routes'
    | '/sandbox-instances'
    | '/security-groups'
    | '/subnets'
    | '/vector-stores'
    | '/vm-instances'
    | '/volumes'
    | '/vpcs'
    | '/objects/$bucketId/$objectId'
    | '/objects/$bucketId/'
    | '/vm-instances/$instanceId/volumes/$volumeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login/callback'
    | '/'
    | '/login'
    | '/container-instances/$instanceId'
    | '/filesystems/$filesystemId'
    | '/gpu-instances/$instanceId'
    | '/inference/$serviceId'
    | '/k8s-clusters/$clusterId'
    | '/kb/$kbId'
    | '/load-balancers/$loadBalancerId'
    | '/models/$modelId'
    | '/routes/$routeId'
    | '/sandbox-instances/$instanceId'
    | '/security-groups/$securityGroupId'
    | '/subnets/$subnetId'
    | '/vector-stores/$vectorStoreId'
    | '/vm-instances/$instanceId'
    | '/volumes/$volumeId'
    | '/vpcs/$vpcId'
    | '/container-instances'
    | '/filesystems'
    | '/gpu-instances'
    | '/gpu-inventory'
    | '/images'
    | '/inference'
    | '/k8s-clusters'
    | '/kb'
    | '/load-balancers'
    | '/models'
    | '/objects'
    | '/overview-compute'
    | '/registry'
    | '/routes'
    | '/sandbox-instances'
    | '/security-groups'
    | '/subnets'
    | '/vector-stores'
    | '/vm-instances'
    | '/volumes'
    | '/vpcs'
    | '/objects/$bucketId/$objectId'
    | '/objects/$bucketId'
    | '/vm-instances/$instanceId/volumes/$volumeId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/login/callback'
    | '/_authenticated/'
    | '/login/'
    | '/_authenticated/container-instances/$instanceId'
    | '/_authenticated/filesystems/$filesystemId'
    | '/_authenticated/gpu-instances/$instanceId'
    | '/_authenticated/inference/$serviceId'
    | '/_authenticated/k8s-clusters/$clusterId'
    | '/_authenticated/kb/$kbId'
    | '/_authenticated/load-balancers/$loadBalancerId'
    | '/_authenticated/models/$modelId'
    | '/_authenticated/objects/$bucketId'
    | '/_authenticated/routes/$routeId'
    | '/_authenticated/sandbox-instances/$instanceId'
    | '/_authenticated/security-groups/$securityGroupId'
    | '/_authenticated/subnets/$subnetId'
    | '/_authenticated/vector-stores/$vectorStoreId'
    | '/_authenticated/vm-instances/$instanceId'
    | '/_authenticated/volumes/$volumeId'
    | '/_authenticated/vpcs/$vpcId'
    | '/_authenticated/container-instances/'
    | '/_authenticated/filesystems/'
    | '/_authenticated/gpu-instances/'
    | '/_authenticated/gpu-inventory/'
    | '/_authenticated/images/'
    | '/_authenticated/inference/'
    | '/_authenticated/k8s-clusters/'
    | '/_authenticated/kb/'
    | '/_authenticated/load-balancers/'
    | '/_authenticated/models/'
    | '/_authenticated/objects/'
    | '/_authenticated/overview-compute/'
    | '/_authenticated/registry/'
    | '/_authenticated/routes/'
    | '/_authenticated/sandbox-instances/'
    | '/_authenticated/security-groups/'
    | '/_authenticated/subnets/'
    | '/_authenticated/vector-stores/'
    | '/_authenticated/vm-instances/'
    | '/_authenticated/volumes/'
    | '/_authenticated/vpcs/'
    | '/_authenticated/objects/$bucketId/$objectId'
    | '/_authenticated/objects/$bucketId/'
    | '/_authenticated/vm-instances/$instanceId/volumes/$volumeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/vpcs/': {
      id: '/_authenticated/vpcs/'
      path: '/vpcs'
      fullPath: '/vpcs'
      preLoaderRoute: typeof AuthenticatedVpcsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/volumes/': {
      id: '/_authenticated/volumes/'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof AuthenticatedVolumesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vm-instances/': {
      id: '/_authenticated/vm-instances/'
      path: '/vm-instances'
      fullPath: '/vm-instances'
      preLoaderRoute: typeof AuthenticatedVmInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vector-stores/': {
      id: '/_authenticated/vector-stores/'
      path: '/vector-stores'
      fullPath: '/vector-stores'
      preLoaderRoute: typeof AuthenticatedVectorStoresIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subnets/': {
      id: '/_authenticated/subnets/'
      path: '/subnets'
      fullPath: '/subnets'
      preLoaderRoute: typeof AuthenticatedSubnetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security-groups/': {
      id: '/_authenticated/security-groups/'
      path: '/security-groups'
      fullPath: '/security-groups'
      preLoaderRoute: typeof AuthenticatedSecurityGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandbox-instances/': {
      id: '/_authenticated/sandbox-instances/'
      path: '/sandbox-instances'
      fullPath: '/sandbox-instances'
      preLoaderRoute: typeof AuthenticatedSandboxInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routes/': {
      id: '/_authenticated/routes/'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registry/': {
      id: '/_authenticated/registry/'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof AuthenticatedRegistryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overview-compute/': {
      id: '/_authenticated/overview-compute/'
      path: '/overview-compute'
      fullPath: '/overview-compute'
      preLoaderRoute: typeof AuthenticatedOverviewComputeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objects/': {
      id: '/_authenticated/objects/'
      path: '/objects'
      fullPath: '/objects'
      preLoaderRoute: typeof AuthenticatedObjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models/': {
      id: '/_authenticated/models/'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/load-balancers/': {
      id: '/_authenticated/load-balancers/'
      path: '/load-balancers'
      fullPath: '/load-balancers'
      preLoaderRoute: typeof AuthenticatedLoadBalancersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kb/': {
      id: '/_authenticated/kb/'
      path: '/kb'
      fullPath: '/kb'
      preLoaderRoute: typeof AuthenticatedKbIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/k8s-clusters/': {
      id: '/_authenticated/k8s-clusters/'
      path: '/k8s-clusters'
      fullPath: '/k8s-clusters'
      preLoaderRoute: typeof AuthenticatedK8sClustersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inference/': {
      id: '/_authenticated/inference/'
      path: '/inference'
      fullPath: '/inference'
      preLoaderRoute: typeof AuthenticatedInferenceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/images/': {
      id: '/_authenticated/images/'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AuthenticatedImagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gpu-inventory/': {
      id: '/_authenticated/gpu-inventory/'
      path: '/gpu-inventory'
      fullPath: '/gpu-inventory'
      preLoaderRoute: typeof AuthenticatedGpuInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gpu-instances/': {
      id: '/_authenticated/gpu-instances/'
      path: '/gpu-instances'
      fullPath: '/gpu-instances'
      preLoaderRoute: typeof AuthenticatedGpuInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/filesystems/': {
      id: '/_authenticated/filesystems/'
      path: '/filesystems'
      fullPath: '/filesystems'
      preLoaderRoute: typeof AuthenticatedFilesystemsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/container-instances/': {
      id: '/_authenticated/container-instances/'
      path: '/container-instances'
      fullPath: '/container-instances'
      preLoaderRoute: typeof AuthenticatedContainerInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vpcs/$vpcId': {
      id: '/_authenticated/vpcs/$vpcId'
      path: '/vpcs/$vpcId'
      fullPath: '/vpcs/$vpcId'
      preLoaderRoute: typeof AuthenticatedVpcsVpcIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/volumes/$volumeId': {
      id: '/_authenticated/volumes/$volumeId'
      path: '/volumes/$volumeId'
      fullPath: '/volumes/$volumeId'
      preLoaderRoute: typeof AuthenticatedVolumesVolumeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vm-instances/$instanceId': {
      id: '/_authenticated/vm-instances/$instanceId'
      path: '/vm-instances/$instanceId'
      fullPath: '/vm-instances/$instanceId'
      preLoaderRoute: typeof AuthenticatedVmInstancesInstanceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vector-stores/$vectorStoreId': {
      id: '/_authenticated/vector-stores/$vectorStoreId'
      path: '/vector-stores/$vectorStoreId'
      fullPath: '/vector-stores/$vectorStoreId'
      preLoaderRoute: typeof AuthenticatedVectorStoresVectorStoreIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subnets/$subnetId': {
      id: '/_authenticated/subnets/$subnetId'
      path: '/subnets/$subnetId'
      fullPath: '/subnets/$subnetId'
      preLoaderRoute: typeof AuthenticatedSubnetsSubnetIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security-groups/$securityGroupId': {
      id: '/_authenticated/security-groups/$securityGroupId'
      path: '/security-groups/$securityGroupId'
      fullPath: '/security-groups/$securityGroupId'
      preLoaderRoute: typeof AuthenticatedSecurityGroupsSecurityGroupIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandbox-instances/$instanceId': {
      id: '/_authenticated/sandbox-instances/$instanceId'
      path: '/sandbox-instances/$instanceId'
      fullPath: '/sandbox-instances/$instanceId'
      preLoaderRoute: typeof AuthenticatedSandboxInstancesInstanceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routes/$routeId': {
      id: '/_authenticated/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof AuthenticatedRoutesRouteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objects/$bucketId': {
      id: '/_authenticated/objects/$bucketId'
      path: '/objects/$bucketId'
      fullPath: '/objects/$bucketId'
      preLoaderRoute: typeof AuthenticatedObjectsBucketIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models/$modelId': {
      id: '/_authenticated/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof AuthenticatedModelsModelIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/load-balancers/$loadBalancerId': {
      id: '/_authenticated/load-balancers/$loadBalancerId'
      path: '/load-balancers/$loadBalancerId'
      fullPath: '/load-balancers/$loadBalancerId'
      preLoaderRoute: typeof AuthenticatedLoadBalancersLoadBalancerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kb/$kbId': {
      id: '/_authenticated/kb/$kbId'
      path: '/kb/$kbId'
      fullPath: '/kb/$kbId'
      preLoaderRoute: typeof AuthenticatedKbKbIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/k8s-clusters/$clusterId': {
      id: '/_authenticated/k8s-clusters/$clusterId'
      path: '/k8s-clusters/$clusterId'
      fullPath: '/k8s-clusters/$clusterId'
      preLoaderRoute: typeof AuthenticatedK8sClustersClusterIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inference/$serviceId': {
      id: '/_authenticated/inference/$serviceId'
      path: '/inference/$serviceId'
      fullPath: '/inference/$serviceId'
      preLoaderRoute: typeof AuthenticatedInferenceServiceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gpu-instances/$instanceId': {
      id: '/_authenticated/gpu-instances/$instanceId'
      path: '/gpu-instances/$instanceId'
      fullPath: '/gpu-instances/$instanceId'
      preLoaderRoute: typeof AuthenticatedGpuInstancesInstanceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/filesystems/$filesystemId': {
      id: '/_authenticated/filesystems/$filesystemId'
      path: '/filesystems/$filesystemId'
      fullPath: '/filesystems/$filesystemId'
      preLoaderRoute: typeof AuthenticatedFilesystemsFilesystemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/container-instances/$instanceId': {
      id: '/_authenticated/container-instances/$instanceId'
      path: '/container-instances/$instanceId'
      fullPath: '/container-instances/$instanceId'
      preLoaderRoute: typeof AuthenticatedContainerInstancesInstanceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objects/$bucketId/': {
      id: '/_authenticated/objects/$bucketId/'
      path: '/'
      fullPath: '/objects/$bucketId/'
      preLoaderRoute: typeof AuthenticatedObjectsBucketIdIndexRouteImport
      parentRoute: typeof AuthenticatedObjectsBucketIdRoute
    }
    '/_authenticated/objects/$bucketId/$objectId': {
      id: '/_authenticated/objects/$bucketId/$objectId'
      path: '/$objectId'
      fullPath: '/objects/$bucketId/$objectId'
      preLoaderRoute: typeof AuthenticatedObjectsBucketIdObjectIdRouteImport
      parentRoute: typeof AuthenticatedObjectsBucketIdRoute
    }
    '/_authenticated/vm-instances/$instanceId/volumes/$volumeId': {
      id: '/_authenticated/vm-instances/$instanceId/volumes/$volumeId'
      path: '/volumes/$volumeId'
      fullPath: '/vm-instances/$instanceId/volumes/$volumeId'
      preLoaderRoute: typeof AuthenticatedVmInstancesInstanceIdVolumesVolumeIdRouteImport
      parentRoute: typeof AuthenticatedVmInstancesInstanceIdRoute
    }
  }
}

interface AuthenticatedObjectsBucketIdRouteChildren {
  AuthenticatedObjectsBucketIdObjectIdRoute: typeof AuthenticatedObjectsBucketIdObjectIdRoute
  AuthenticatedObjectsBucketIdIndexRoute: typeof AuthenticatedObjectsBucketIdIndexRoute
}

const AuthenticatedObjectsBucketIdRouteChildren: AuthenticatedObjectsBucketIdRouteChildren =
  {
    AuthenticatedObjectsBucketIdObjectIdRoute:
      AuthenticatedObjectsBucketIdObjectIdRoute,
    AuthenticatedObjectsBucketIdIndexRoute:
      AuthenticatedObjectsBucketIdIndexRoute,
  }

const AuthenticatedObjectsBucketIdRouteWithChildren =
  AuthenticatedObjectsBucketIdRoute._addFileChildren(
    AuthenticatedObjectsBucketIdRouteChildren,
  )

interface AuthenticatedVmInstancesInstanceIdRouteChildren {
  AuthenticatedVmInstancesInstanceIdVolumesVolumeIdRoute: typeof AuthenticatedVmInstancesInstanceIdVolumesVolumeIdRoute
}

const AuthenticatedVmInstancesInstanceIdRouteChildren: AuthenticatedVmInstancesInstanceIdRouteChildren =
  {
    AuthenticatedVmInstancesInstanceIdVolumesVolumeIdRoute:
      AuthenticatedVmInstancesInstanceIdVolumesVolumeIdRoute,
  }

const AuthenticatedVmInstancesInstanceIdRouteWithChildren =
  AuthenticatedVmInstancesInstanceIdRoute._addFileChildren(
    AuthenticatedVmInstancesInstanceIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedContainerInstancesInstanceIdRoute: typeof AuthenticatedContainerInstancesInstanceIdRoute
  AuthenticatedFilesystemsFilesystemIdRoute: typeof AuthenticatedFilesystemsFilesystemIdRoute
  AuthenticatedGpuInstancesInstanceIdRoute: typeof AuthenticatedGpuInstancesInstanceIdRoute
  AuthenticatedInferenceServiceIdRoute: typeof AuthenticatedInferenceServiceIdRoute
  AuthenticatedK8sClustersClusterIdRoute: typeof AuthenticatedK8sClustersClusterIdRoute
  AuthenticatedKbKbIdRoute: typeof AuthenticatedKbKbIdRoute
  AuthenticatedLoadBalancersLoadBalancerIdRoute: typeof AuthenticatedLoadBalancersLoadBalancerIdRoute
  AuthenticatedModelsModelIdRoute: typeof AuthenticatedModelsModelIdRoute
  AuthenticatedObjectsBucketIdRoute: typeof AuthenticatedObjectsBucketIdRouteWithChildren
  AuthenticatedRoutesRouteIdRoute: typeof AuthenticatedRoutesRouteIdRoute
  AuthenticatedSandboxInstancesInstanceIdRoute: typeof AuthenticatedSandboxInstancesInstanceIdRoute
  AuthenticatedSecurityGroupsSecurityGroupIdRoute: typeof AuthenticatedSecurityGroupsSecurityGroupIdRoute
  AuthenticatedSubnetsSubnetIdRoute: typeof AuthenticatedSubnetsSubnetIdRoute
  AuthenticatedVectorStoresVectorStoreIdRoute: typeof AuthenticatedVectorStoresVectorStoreIdRoute
  AuthenticatedVmInstancesInstanceIdRoute: typeof AuthenticatedVmInstancesInstanceIdRouteWithChildren
  AuthenticatedVolumesVolumeIdRoute: typeof AuthenticatedVolumesVolumeIdRoute
  AuthenticatedVpcsVpcIdRoute: typeof AuthenticatedVpcsVpcIdRoute
  AuthenticatedContainerInstancesIndexRoute: typeof AuthenticatedContainerInstancesIndexRoute
  AuthenticatedFilesystemsIndexRoute: typeof AuthenticatedFilesystemsIndexRoute
  AuthenticatedGpuInstancesIndexRoute: typeof AuthenticatedGpuInstancesIndexRoute
  AuthenticatedGpuInventoryIndexRoute: typeof AuthenticatedGpuInventoryIndexRoute
  AuthenticatedImagesIndexRoute: typeof AuthenticatedImagesIndexRoute
  AuthenticatedInferenceIndexRoute: typeof AuthenticatedInferenceIndexRoute
  AuthenticatedK8sClustersIndexRoute: typeof AuthenticatedK8sClustersIndexRoute
  AuthenticatedKbIndexRoute: typeof AuthenticatedKbIndexRoute
  AuthenticatedLoadBalancersIndexRoute: typeof AuthenticatedLoadBalancersIndexRoute
  AuthenticatedModelsIndexRoute: typeof AuthenticatedModelsIndexRoute
  AuthenticatedObjectsIndexRoute: typeof AuthenticatedObjectsIndexRoute
  AuthenticatedOverviewComputeIndexRoute: typeof AuthenticatedOverviewComputeIndexRoute
  AuthenticatedRegistryIndexRoute: typeof AuthenticatedRegistryIndexRoute
  AuthenticatedRoutesIndexRoute: typeof AuthenticatedRoutesIndexRoute
  AuthenticatedSandboxInstancesIndexRoute: typeof AuthenticatedSandboxInstancesIndexRoute
  AuthenticatedSecurityGroupsIndexRoute: typeof AuthenticatedSecurityGroupsIndexRoute
  AuthenticatedSubnetsIndexRoute: typeof AuthenticatedSubnetsIndexRoute
  AuthenticatedVectorStoresIndexRoute: typeof AuthenticatedVectorStoresIndexRoute
  AuthenticatedVmInstancesIndexRoute: typeof AuthenticatedVmInstancesIndexRoute
  AuthenticatedVolumesIndexRoute: typeof AuthenticatedVolumesIndexRoute
  AuthenticatedVpcsIndexRoute: typeof AuthenticatedVpcsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedContainerInstancesInstanceIdRoute:
    AuthenticatedContainerInstancesInstanceIdRoute,
  AuthenticatedFilesystemsFilesystemIdRoute:
    AuthenticatedFilesystemsFilesystemIdRoute,
  AuthenticatedGpuInstancesInstanceIdRoute:
    AuthenticatedGpuInstancesInstanceIdRoute,
  AuthenticatedInferenceServiceIdRoute: AuthenticatedInferenceServiceIdRoute,
  AuthenticatedK8sClustersClusterIdRoute:
    AuthenticatedK8sClustersClusterIdRoute,
  AuthenticatedKbKbIdRoute: AuthenticatedKbKbIdRoute,
  AuthenticatedLoadBalancersLoadBalancerIdRoute:
    AuthenticatedLoadBalancersLoadBalancerIdRoute,
  AuthenticatedModelsModelIdRoute: AuthenticatedModelsModelIdRoute,
  AuthenticatedObjectsBucketIdRoute:
    AuthenticatedObjectsBucketIdRouteWithChildren,
  AuthenticatedRoutesRouteIdRoute: AuthenticatedRoutesRouteIdRoute,
  AuthenticatedSandboxInstancesInstanceIdRoute:
    AuthenticatedSandboxInstancesInstanceIdRoute,
  AuthenticatedSecurityGroupsSecurityGroupIdRoute:
    AuthenticatedSecurityGroupsSecurityGroupIdRoute,
  AuthenticatedSubnetsSubnetIdRoute: AuthenticatedSubnetsSubnetIdRoute,
  AuthenticatedVectorStoresVectorStoreIdRoute:
    AuthenticatedVectorStoresVectorStoreIdRoute,
  AuthenticatedVmInstancesInstanceIdRoute:
    AuthenticatedVmInstancesInstanceIdRouteWithChildren,
  AuthenticatedVolumesVolumeIdRoute: AuthenticatedVolumesVolumeIdRoute,
  AuthenticatedVpcsVpcIdRoute: AuthenticatedVpcsVpcIdRoute,
  AuthenticatedContainerInstancesIndexRoute:
    AuthenticatedContainerInstancesIndexRoute,
  AuthenticatedFilesystemsIndexRoute: AuthenticatedFilesystemsIndexRoute,
  AuthenticatedGpuInstancesIndexRoute: AuthenticatedGpuInstancesIndexRoute,
  AuthenticatedGpuInventoryIndexRoute: AuthenticatedGpuInventoryIndexRoute,
  AuthenticatedImagesIndexRoute: AuthenticatedImagesIndexRoute,
  AuthenticatedInferenceIndexRoute: AuthenticatedInferenceIndexRoute,
  AuthenticatedK8sClustersIndexRoute: AuthenticatedK8sClustersIndexRoute,
  AuthenticatedKbIndexRoute: AuthenticatedKbIndexRoute,
  AuthenticatedLoadBalancersIndexRoute: AuthenticatedLoadBalancersIndexRoute,
  AuthenticatedModelsIndexRoute: AuthenticatedModelsIndexRoute,
  AuthenticatedObjectsIndexRoute: AuthenticatedObjectsIndexRoute,
  AuthenticatedOverviewComputeIndexRoute:
    AuthenticatedOverviewComputeIndexRoute,
  AuthenticatedRegistryIndexRoute: AuthenticatedRegistryIndexRoute,
  AuthenticatedRoutesIndexRoute: AuthenticatedRoutesIndexRoute,
  AuthenticatedSandboxInstancesIndexRoute:
    AuthenticatedSandboxInstancesIndexRoute,
  AuthenticatedSecurityGroupsIndexRoute: AuthenticatedSecurityGroupsIndexRoute,
  AuthenticatedSubnetsIndexRoute: AuthenticatedSubnetsIndexRoute,
  AuthenticatedVectorStoresIndexRoute: AuthenticatedVectorStoresIndexRoute,
  AuthenticatedVmInstancesIndexRoute: AuthenticatedVmInstancesIndexRoute,
  AuthenticatedVolumesIndexRoute: AuthenticatedVolumesIndexRoute,
  AuthenticatedVpcsIndexRoute: AuthenticatedVpcsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginCallbackRoute: typeof LoginCallbackRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginCallbackRoute: LoginCallbackRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
