/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LoginCallbackRouteImport } from './routes/login.callback'
import { Route as AuthenticatedVolumesIndexRouteImport } from './routes/_authenticated/volumes/index'
import { Route as AuthenticatedVectorStoresIndexRouteImport } from './routes/_authenticated/vector-stores/index'
import { Route as AuthenticatedSandboxTemplatesIndexRouteImport } from './routes/_authenticated/sandbox-templates/index'
import { Route as AuthenticatedRegistryIndexRouteImport } from './routes/_authenticated/registry/index'
import { Route as AuthenticatedObjectsIndexRouteImport } from './routes/_authenticated/objects/index'
import { Route as AuthenticatedModelsIndexRouteImport } from './routes/_authenticated/models/index'
import { Route as AuthenticatedKbIndexRouteImport } from './routes/_authenticated/kb/index'
import { Route as AuthenticatedK8sClustersIndexRouteImport } from './routes/_authenticated/k8s-clusters/index'
import { Route as AuthenticatedInstancesIndexRouteImport } from './routes/_authenticated/instances/index'
import { Route as AuthenticatedInferenceIndexRouteImport } from './routes/_authenticated/inference/index'
import { Route as AuthenticatedImagesIndexRouteImport } from './routes/_authenticated/images/index'
import { Route as AuthenticatedGpuInventoryIndexRouteImport } from './routes/_authenticated/gpu-inventory/index'
import { Route as AuthenticatedGpuInstancesIndexRouteImport } from './routes/_authenticated/gpu-instances/index'
import { Route as AuthenticatedFilesystemsIndexRouteImport } from './routes/_authenticated/filesystems/index'
import { Route as InstancesTerminalInstanceIdRouteImport } from './routes/instances/terminal/$instanceId'
import { Route as InstancesConsoleInstanceIdRouteImport } from './routes/instances/console/$instanceId'
import { Route as AuthenticatedVolumesVolumeIdRouteImport } from './routes/_authenticated/volumes/$volumeId'
import { Route as AuthenticatedVectorStoresVectorStoreIdRouteImport } from './routes/_authenticated/vector-stores/$vectorStoreId'
import { Route as AuthenticatedObjectsBucketIdRouteImport } from './routes/_authenticated/objects/$bucketId'
import { Route as AuthenticatedModelsModelIdRouteImport } from './routes/_authenticated/models/$modelId'
import { Route as AuthenticatedKbKbIdRouteImport } from './routes/_authenticated/kb/$kbId'
import { Route as AuthenticatedK8sClustersClusterIdRouteImport } from './routes/_authenticated/k8s-clusters/$clusterId'
import { Route as AuthenticatedInstancesVmRouteImport } from './routes/_authenticated/instances/vm'
import { Route as AuthenticatedInstancesSandboxRouteImport } from './routes/_authenticated/instances/sandbox'
import { Route as AuthenticatedInstancesContainerRouteImport } from './routes/_authenticated/instances/container'
import { Route as AuthenticatedInstancesInstanceIdRouteImport } from './routes/_authenticated/instances/$instanceId'
import { Route as AuthenticatedInstanceOperationsOperationIdRouteImport } from './routes/_authenticated/instance-operations/$operationId'
import { Route as AuthenticatedInferencePoliciesRouteImport } from './routes/_authenticated/inference/policies'
import { Route as AuthenticatedInferenceServiceIdRouteImport } from './routes/_authenticated/inference/$serviceId'
import { Route as AuthenticatedFilesystemsFilesystemIdRouteImport } from './routes/_authenticated/filesystems/$filesystemId'
import { Route as AuthenticatedComputeOverviewRouteImport } from './routes/_authenticated/compute/overview'
import { Route as AuthenticatedObjectsBucketIdIndexRouteImport } from './routes/_authenticated/objects/$bucketId/index'
import { Route as AuthenticatedNetworksVpcsIndexRouteImport } from './routes/_authenticated/networks/vpcs/index'
import { Route as AuthenticatedNetworksSubnetsIndexRouteImport } from './routes/_authenticated/networks/subnets/index'
import { Route as AuthenticatedNetworksSecurityGroupsIndexRouteImport } from './routes/_authenticated/networks/security-groups/index'
import { Route as AuthenticatedNetworksRoutesIndexRouteImport } from './routes/_authenticated/networks/routes/index'
import { Route as AuthenticatedNetworksLoadBalancersIndexRouteImport } from './routes/_authenticated/networks/load-balancers/index'
import { Route as AuthenticatedObjectsBucketIdObjectIdRouteImport } from './routes/_authenticated/objects/$bucketId/$objectId'
import { Route as AuthenticatedNetworksVpcsVpcIdRouteImport } from './routes/_authenticated/networks/vpcs/$vpcId'
import { Route as AuthenticatedNetworksSubnetsSubnetIdRouteImport } from './routes/_authenticated/networks/subnets/$subnetId'
import { Route as AuthenticatedNetworksSecurityGroupsSecurityGroupIdRouteImport } from './routes/_authenticated/networks/security-groups/$securityGroupId'
import { Route as AuthenticatedNetworksRoutesRouteIdRouteImport } from './routes/_authenticated/networks/routes/$routeId'
import { Route as AuthenticatedNetworksLoadBalancersLoadBalancerIdRouteImport } from './routes/_authenticated/networks/load-balancers/$loadBalancerId'
import { Route as AuthenticatedInstancesVmCreateRouteImport } from './routes/_authenticated/instances/vm/create'
import { Route as AuthenticatedInstancesVmInstanceIdRouteImport } from './routes/_authenticated/instances/vm/$instanceId'
import { Route as AuthenticatedInstancesSandboxCreateRouteImport } from './routes/_authenticated/instances/sandbox/create'
import { Route as AuthenticatedInstancesSandboxInstanceIdRouteImport } from './routes/_authenticated/instances/sandbox/$instanceId'
import { Route as AuthenticatedInstancesContainerInstanceIdRouteImport } from './routes/_authenticated/instances/container/$instanceId'
import { Route as AuthenticatedInstancesInstanceIdOperationsRouteImport } from './routes/_authenticated/instances/$instanceId.operations'
import { Route as AuthenticatedInferencePoliciesPolicyIdRouteImport } from './routes/_authenticated/inference/policies.$policyId'
import { Route as AuthenticatedInstancesContainerCreateRouteRouteImport } from './routes/_authenticated/instances/container/create/route'
import { Route as AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRouteImport } from './routes/_authenticated/instances/vm/$instanceId/volumes/$volumeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedVolumesIndexRoute =
  AuthenticatedVolumesIndexRouteImport.update({
    id: '/volumes/',
    path: '/volumes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVectorStoresIndexRoute =
  AuthenticatedVectorStoresIndexRouteImport.update({
    id: '/vector-stores/',
    path: '/vector-stores/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxTemplatesIndexRoute =
  AuthenticatedSandboxTemplatesIndexRouteImport.update({
    id: '/sandbox-templates/',
    path: '/sandbox-templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistryIndexRoute =
  AuthenticatedRegistryIndexRouteImport.update({
    id: '/registry/',
    path: '/registry/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObjectsIndexRoute =
  AuthenticatedObjectsIndexRouteImport.update({
    id: '/objects/',
    path: '/objects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModelsIndexRoute =
  AuthenticatedModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKbIndexRoute = AuthenticatedKbIndexRouteImport.update({
  id: '/kb/',
  path: '/kb/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedK8sClustersIndexRoute =
  AuthenticatedK8sClustersIndexRouteImport.update({
    id: '/k8s-clusters/',
    path: '/k8s-clusters/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesIndexRoute =
  AuthenticatedInstancesIndexRouteImport.update({
    id: '/instances/',
    path: '/instances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInferenceIndexRoute =
  AuthenticatedInferenceIndexRouteImport.update({
    id: '/inference/',
    path: '/inference/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImagesIndexRoute =
  AuthenticatedImagesIndexRouteImport.update({
    id: '/images/',
    path: '/images/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGpuInventoryIndexRoute =
  AuthenticatedGpuInventoryIndexRouteImport.update({
    id: '/gpu-inventory/',
    path: '/gpu-inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGpuInstancesIndexRoute =
  AuthenticatedGpuInstancesIndexRouteImport.update({
    id: '/gpu-instances/',
    path: '/gpu-instances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilesystemsIndexRoute =
  AuthenticatedFilesystemsIndexRouteImport.update({
    id: '/filesystems/',
    path: '/filesystems/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const InstancesTerminalInstanceIdRoute =
  InstancesTerminalInstanceIdRouteImport.update({
    id: '/instances/terminal/$instanceId',
    path: '/instances/terminal/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstancesConsoleInstanceIdRoute =
  InstancesConsoleInstanceIdRouteImport.update({
    id: '/instances/console/$instanceId',
    path: '/instances/console/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedVolumesVolumeIdRoute =
  AuthenticatedVolumesVolumeIdRouteImport.update({
    id: '/volumes/$volumeId',
    path: '/volumes/$volumeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVectorStoresVectorStoreIdRoute =
  AuthenticatedVectorStoresVectorStoreIdRouteImport.update({
    id: '/vector-stores/$vectorStoreId',
    path: '/vector-stores/$vectorStoreId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObjectsBucketIdRoute =
  AuthenticatedObjectsBucketIdRouteImport.update({
    id: '/objects/$bucketId',
    path: '/objects/$bucketId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModelsModelIdRoute =
  AuthenticatedModelsModelIdRouteImport.update({
    id: '/models/$modelId',
    path: '/models/$modelId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKbKbIdRoute = AuthenticatedKbKbIdRouteImport.update({
  id: '/kb/$kbId',
  path: '/kb/$kbId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedK8sClustersClusterIdRoute =
  AuthenticatedK8sClustersClusterIdRouteImport.update({
    id: '/k8s-clusters/$clusterId',
    path: '/k8s-clusters/$clusterId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesVmRoute =
  AuthenticatedInstancesVmRouteImport.update({
    id: '/instances/vm',
    path: '/instances/vm',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesSandboxRoute =
  AuthenticatedInstancesSandboxRouteImport.update({
    id: '/instances/sandbox',
    path: '/instances/sandbox',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesContainerRoute =
  AuthenticatedInstancesContainerRouteImport.update({
    id: '/instances/container',
    path: '/instances/container',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesInstanceIdRoute =
  AuthenticatedInstancesInstanceIdRouteImport.update({
    id: '/instances/$instanceId',
    path: '/instances/$instanceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstanceOperationsOperationIdRoute =
  AuthenticatedInstanceOperationsOperationIdRouteImport.update({
    id: '/instance-operations/$operationId',
    path: '/instance-operations/$operationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInferencePoliciesRoute =
  AuthenticatedInferencePoliciesRouteImport.update({
    id: '/inference/policies',
    path: '/inference/policies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInferenceServiceIdRoute =
  AuthenticatedInferenceServiceIdRouteImport.update({
    id: '/inference/$serviceId',
    path: '/inference/$serviceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilesystemsFilesystemIdRoute =
  AuthenticatedFilesystemsFilesystemIdRouteImport.update({
    id: '/filesystems/$filesystemId',
    path: '/filesystems/$filesystemId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComputeOverviewRoute =
  AuthenticatedComputeOverviewRouteImport.update({
    id: '/compute/overview',
    path: '/compute/overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObjectsBucketIdIndexRoute =
  AuthenticatedObjectsBucketIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedObjectsBucketIdRoute,
  } as any)
const AuthenticatedNetworksVpcsIndexRoute =
  AuthenticatedNetworksVpcsIndexRouteImport.update({
    id: '/networks/vpcs/',
    path: '/networks/vpcs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksSubnetsIndexRoute =
  AuthenticatedNetworksSubnetsIndexRouteImport.update({
    id: '/networks/subnets/',
    path: '/networks/subnets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksSecurityGroupsIndexRoute =
  AuthenticatedNetworksSecurityGroupsIndexRouteImport.update({
    id: '/networks/security-groups/',
    path: '/networks/security-groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksRoutesIndexRoute =
  AuthenticatedNetworksRoutesIndexRouteImport.update({
    id: '/networks/routes/',
    path: '/networks/routes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksLoadBalancersIndexRoute =
  AuthenticatedNetworksLoadBalancersIndexRouteImport.update({
    id: '/networks/load-balancers/',
    path: '/networks/load-balancers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObjectsBucketIdObjectIdRoute =
  AuthenticatedObjectsBucketIdObjectIdRouteImport.update({
    id: '/$objectId',
    path: '/$objectId',
    getParentRoute: () => AuthenticatedObjectsBucketIdRoute,
  } as any)
const AuthenticatedNetworksVpcsVpcIdRoute =
  AuthenticatedNetworksVpcsVpcIdRouteImport.update({
    id: '/networks/vpcs/$vpcId',
    path: '/networks/vpcs/$vpcId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksSubnetsSubnetIdRoute =
  AuthenticatedNetworksSubnetsSubnetIdRouteImport.update({
    id: '/networks/subnets/$subnetId',
    path: '/networks/subnets/$subnetId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute =
  AuthenticatedNetworksSecurityGroupsSecurityGroupIdRouteImport.update({
    id: '/networks/security-groups/$securityGroupId',
    path: '/networks/security-groups/$securityGroupId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksRoutesRouteIdRoute =
  AuthenticatedNetworksRoutesRouteIdRouteImport.update({
    id: '/networks/routes/$routeId',
    path: '/networks/routes/$routeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute =
  AuthenticatedNetworksLoadBalancersLoadBalancerIdRouteImport.update({
    id: '/networks/load-balancers/$loadBalancerId',
    path: '/networks/load-balancers/$loadBalancerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesVmCreateRoute =
  AuthenticatedInstancesVmCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedInstancesVmRoute,
  } as any)
const AuthenticatedInstancesVmInstanceIdRoute =
  AuthenticatedInstancesVmInstanceIdRouteImport.update({
    id: '/$instanceId',
    path: '/$instanceId',
    getParentRoute: () => AuthenticatedInstancesVmRoute,
  } as any)
const AuthenticatedInstancesSandboxCreateRoute =
  AuthenticatedInstancesSandboxCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedInstancesSandboxRoute,
  } as any)
const AuthenticatedInstancesSandboxInstanceIdRoute =
  AuthenticatedInstancesSandboxInstanceIdRouteImport.update({
    id: '/$instanceId',
    path: '/$instanceId',
    getParentRoute: () => AuthenticatedInstancesSandboxRoute,
  } as any)
const AuthenticatedInstancesContainerInstanceIdRoute =
  AuthenticatedInstancesContainerInstanceIdRouteImport.update({
    id: '/$instanceId',
    path: '/$instanceId',
    getParentRoute: () => AuthenticatedInstancesContainerRoute,
  } as any)
const AuthenticatedInstancesInstanceIdOperationsRoute =
  AuthenticatedInstancesInstanceIdOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedInstancesInstanceIdRoute,
  } as any)
const AuthenticatedInferencePoliciesPolicyIdRoute =
  AuthenticatedInferencePoliciesPolicyIdRouteImport.update({
    id: '/$policyId',
    path: '/$policyId',
    getParentRoute: () => AuthenticatedInferencePoliciesRoute,
  } as any)
const AuthenticatedInstancesContainerCreateRouteRoute =
  AuthenticatedInstancesContainerCreateRouteRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedInstancesContainerRoute,
  } as any)
const AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute =
  AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRouteImport.update({
    id: '/volumes/$volumeId',
    path: '/volumes/$volumeId',
    getParentRoute: () => AuthenticatedInstancesVmInstanceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteWithChildren
  '/login/callback': typeof LoginCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/compute/overview': typeof AuthenticatedComputeOverviewRoute
  '/filesystems/$filesystemId': typeof AuthenticatedFilesystemsFilesystemIdRoute
  '/inference/$serviceId': typeof AuthenticatedInferenceServiceIdRoute
  '/inference/policies': typeof AuthenticatedInferencePoliciesRouteWithChildren
  '/instance-operations/$operationId': typeof AuthenticatedInstanceOperationsOperationIdRoute
  '/instances/$instanceId': typeof AuthenticatedInstancesInstanceIdRouteWithChildren
  '/instances/container': typeof AuthenticatedInstancesContainerRouteWithChildren
  '/instances/sandbox': typeof AuthenticatedInstancesSandboxRouteWithChildren
  '/instances/vm': typeof AuthenticatedInstancesVmRouteWithChildren
  '/k8s-clusters/$clusterId': typeof AuthenticatedK8sClustersClusterIdRoute
  '/kb/$kbId': typeof AuthenticatedKbKbIdRoute
  '/models/$modelId': typeof AuthenticatedModelsModelIdRoute
  '/objects/$bucketId': typeof AuthenticatedObjectsBucketIdRouteWithChildren
  '/vector-stores/$vectorStoreId': typeof AuthenticatedVectorStoresVectorStoreIdRoute
  '/volumes/$volumeId': typeof AuthenticatedVolumesVolumeIdRoute
  '/instances/console/$instanceId': typeof InstancesConsoleInstanceIdRoute
  '/instances/terminal/$instanceId': typeof InstancesTerminalInstanceIdRoute
  '/filesystems': typeof AuthenticatedFilesystemsIndexRoute
  '/gpu-instances': typeof AuthenticatedGpuInstancesIndexRoute
  '/gpu-inventory': typeof AuthenticatedGpuInventoryIndexRoute
  '/images': typeof AuthenticatedImagesIndexRoute
  '/inference': typeof AuthenticatedInferenceIndexRoute
  '/instances': typeof AuthenticatedInstancesIndexRoute
  '/k8s-clusters': typeof AuthenticatedK8sClustersIndexRoute
  '/kb': typeof AuthenticatedKbIndexRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/objects': typeof AuthenticatedObjectsIndexRoute
  '/registry': typeof AuthenticatedRegistryIndexRoute
  '/sandbox-templates': typeof AuthenticatedSandboxTemplatesIndexRoute
  '/vector-stores': typeof AuthenticatedVectorStoresIndexRoute
  '/volumes': typeof AuthenticatedVolumesIndexRoute
  '/instances/container/create': typeof AuthenticatedInstancesContainerCreateRouteRoute
  '/inference/policies/$policyId': typeof AuthenticatedInferencePoliciesPolicyIdRoute
  '/instances/$instanceId/operations': typeof AuthenticatedInstancesInstanceIdOperationsRoute
  '/instances/container/$instanceId': typeof AuthenticatedInstancesContainerInstanceIdRoute
  '/instances/sandbox/$instanceId': typeof AuthenticatedInstancesSandboxInstanceIdRoute
  '/instances/sandbox/create': typeof AuthenticatedInstancesSandboxCreateRoute
  '/instances/vm/$instanceId': typeof AuthenticatedInstancesVmInstanceIdRouteWithChildren
  '/instances/vm/create': typeof AuthenticatedInstancesVmCreateRoute
  '/networks/load-balancers/$loadBalancerId': typeof AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute
  '/networks/routes/$routeId': typeof AuthenticatedNetworksRoutesRouteIdRoute
  '/networks/security-groups/$securityGroupId': typeof AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute
  '/networks/subnets/$subnetId': typeof AuthenticatedNetworksSubnetsSubnetIdRoute
  '/networks/vpcs/$vpcId': typeof AuthenticatedNetworksVpcsVpcIdRoute
  '/objects/$bucketId/$objectId': typeof AuthenticatedObjectsBucketIdObjectIdRoute
  '/networks/load-balancers': typeof AuthenticatedNetworksLoadBalancersIndexRoute
  '/networks/routes': typeof AuthenticatedNetworksRoutesIndexRoute
  '/networks/security-groups': typeof AuthenticatedNetworksSecurityGroupsIndexRoute
  '/networks/subnets': typeof AuthenticatedNetworksSubnetsIndexRoute
  '/networks/vpcs': typeof AuthenticatedNetworksVpcsIndexRoute
  '/objects/$bucketId/': typeof AuthenticatedObjectsBucketIdIndexRoute
  '/instances/vm/$instanceId/volumes/$volumeId': typeof AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute
}
export interface FileRoutesByTo {
  '/login/callback': typeof LoginCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/compute/overview': typeof AuthenticatedComputeOverviewRoute
  '/filesystems/$filesystemId': typeof AuthenticatedFilesystemsFilesystemIdRoute
  '/inference/$serviceId': typeof AuthenticatedInferenceServiceIdRoute
  '/inference/policies': typeof AuthenticatedInferencePoliciesRouteWithChildren
  '/instance-operations/$operationId': typeof AuthenticatedInstanceOperationsOperationIdRoute
  '/instances/$instanceId': typeof AuthenticatedInstancesInstanceIdRouteWithChildren
  '/instances/container': typeof AuthenticatedInstancesContainerRouteWithChildren
  '/instances/sandbox': typeof AuthenticatedInstancesSandboxRouteWithChildren
  '/instances/vm': typeof AuthenticatedInstancesVmRouteWithChildren
  '/k8s-clusters/$clusterId': typeof AuthenticatedK8sClustersClusterIdRoute
  '/kb/$kbId': typeof AuthenticatedKbKbIdRoute
  '/models/$modelId': typeof AuthenticatedModelsModelIdRoute
  '/vector-stores/$vectorStoreId': typeof AuthenticatedVectorStoresVectorStoreIdRoute
  '/volumes/$volumeId': typeof AuthenticatedVolumesVolumeIdRoute
  '/instances/console/$instanceId': typeof InstancesConsoleInstanceIdRoute
  '/instances/terminal/$instanceId': typeof InstancesTerminalInstanceIdRoute
  '/filesystems': typeof AuthenticatedFilesystemsIndexRoute
  '/gpu-instances': typeof AuthenticatedGpuInstancesIndexRoute
  '/gpu-inventory': typeof AuthenticatedGpuInventoryIndexRoute
  '/images': typeof AuthenticatedImagesIndexRoute
  '/inference': typeof AuthenticatedInferenceIndexRoute
  '/instances': typeof AuthenticatedInstancesIndexRoute
  '/k8s-clusters': typeof AuthenticatedK8sClustersIndexRoute
  '/kb': typeof AuthenticatedKbIndexRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/objects': typeof AuthenticatedObjectsIndexRoute
  '/registry': typeof AuthenticatedRegistryIndexRoute
  '/sandbox-templates': typeof AuthenticatedSandboxTemplatesIndexRoute
  '/vector-stores': typeof AuthenticatedVectorStoresIndexRoute
  '/volumes': typeof AuthenticatedVolumesIndexRoute
  '/instances/container/create': typeof AuthenticatedInstancesContainerCreateRouteRoute
  '/inference/policies/$policyId': typeof AuthenticatedInferencePoliciesPolicyIdRoute
  '/instances/$instanceId/operations': typeof AuthenticatedInstancesInstanceIdOperationsRoute
  '/instances/container/$instanceId': typeof AuthenticatedInstancesContainerInstanceIdRoute
  '/instances/sandbox/$instanceId': typeof AuthenticatedInstancesSandboxInstanceIdRoute
  '/instances/sandbox/create': typeof AuthenticatedInstancesSandboxCreateRoute
  '/instances/vm/$instanceId': typeof AuthenticatedInstancesVmInstanceIdRouteWithChildren
  '/instances/vm/create': typeof AuthenticatedInstancesVmCreateRoute
  '/networks/load-balancers/$loadBalancerId': typeof AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute
  '/networks/routes/$routeId': typeof AuthenticatedNetworksRoutesRouteIdRoute
  '/networks/security-groups/$securityGroupId': typeof AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute
  '/networks/subnets/$subnetId': typeof AuthenticatedNetworksSubnetsSubnetIdRoute
  '/networks/vpcs/$vpcId': typeof AuthenticatedNetworksVpcsVpcIdRoute
  '/objects/$bucketId/$objectId': typeof AuthenticatedObjectsBucketIdObjectIdRoute
  '/networks/load-balancers': typeof AuthenticatedNetworksLoadBalancersIndexRoute
  '/networks/routes': typeof AuthenticatedNetworksRoutesIndexRoute
  '/networks/security-groups': typeof AuthenticatedNetworksSecurityGroupsIndexRoute
  '/networks/subnets': typeof AuthenticatedNetworksSubnetsIndexRoute
  '/networks/vpcs': typeof AuthenticatedNetworksVpcsIndexRoute
  '/objects/$bucketId': typeof AuthenticatedObjectsBucketIdIndexRoute
  '/instances/vm/$instanceId/volumes/$volumeId': typeof AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/login/callback': typeof LoginCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/compute/overview': typeof AuthenticatedComputeOverviewRoute
  '/_authenticated/filesystems/$filesystemId': typeof AuthenticatedFilesystemsFilesystemIdRoute
  '/_authenticated/inference/$serviceId': typeof AuthenticatedInferenceServiceIdRoute
  '/_authenticated/inference/policies': typeof AuthenticatedInferencePoliciesRouteWithChildren
  '/_authenticated/instance-operations/$operationId': typeof AuthenticatedInstanceOperationsOperationIdRoute
  '/_authenticated/instances/$instanceId': typeof AuthenticatedInstancesInstanceIdRouteWithChildren
  '/_authenticated/instances/container': typeof AuthenticatedInstancesContainerRouteWithChildren
  '/_authenticated/instances/sandbox': typeof AuthenticatedInstancesSandboxRouteWithChildren
  '/_authenticated/instances/vm': typeof AuthenticatedInstancesVmRouteWithChildren
  '/_authenticated/k8s-clusters/$clusterId': typeof AuthenticatedK8sClustersClusterIdRoute
  '/_authenticated/kb/$kbId': typeof AuthenticatedKbKbIdRoute
  '/_authenticated/models/$modelId': typeof AuthenticatedModelsModelIdRoute
  '/_authenticated/objects/$bucketId': typeof AuthenticatedObjectsBucketIdRouteWithChildren
  '/_authenticated/vector-stores/$vectorStoreId': typeof AuthenticatedVectorStoresVectorStoreIdRoute
  '/_authenticated/volumes/$volumeId': typeof AuthenticatedVolumesVolumeIdRoute
  '/instances/console/$instanceId': typeof InstancesConsoleInstanceIdRoute
  '/instances/terminal/$instanceId': typeof InstancesTerminalInstanceIdRoute
  '/_authenticated/filesystems/': typeof AuthenticatedFilesystemsIndexRoute
  '/_authenticated/gpu-instances/': typeof AuthenticatedGpuInstancesIndexRoute
  '/_authenticated/gpu-inventory/': typeof AuthenticatedGpuInventoryIndexRoute
  '/_authenticated/images/': typeof AuthenticatedImagesIndexRoute
  '/_authenticated/inference/': typeof AuthenticatedInferenceIndexRoute
  '/_authenticated/instances/': typeof AuthenticatedInstancesIndexRoute
  '/_authenticated/k8s-clusters/': typeof AuthenticatedK8sClustersIndexRoute
  '/_authenticated/kb/': typeof AuthenticatedKbIndexRoute
  '/_authenticated/models/': typeof AuthenticatedModelsIndexRoute
  '/_authenticated/objects/': typeof AuthenticatedObjectsIndexRoute
  '/_authenticated/registry/': typeof AuthenticatedRegistryIndexRoute
  '/_authenticated/sandbox-templates/': typeof AuthenticatedSandboxTemplatesIndexRoute
  '/_authenticated/vector-stores/': typeof AuthenticatedVectorStoresIndexRoute
  '/_authenticated/volumes/': typeof AuthenticatedVolumesIndexRoute
  '/_authenticated/instances/container/create': typeof AuthenticatedInstancesContainerCreateRouteRoute
  '/_authenticated/inference/policies/$policyId': typeof AuthenticatedInferencePoliciesPolicyIdRoute
  '/_authenticated/instances/$instanceId/operations': typeof AuthenticatedInstancesInstanceIdOperationsRoute
  '/_authenticated/instances/container/$instanceId': typeof AuthenticatedInstancesContainerInstanceIdRoute
  '/_authenticated/instances/sandbox/$instanceId': typeof AuthenticatedInstancesSandboxInstanceIdRoute
  '/_authenticated/instances/sandbox/create': typeof AuthenticatedInstancesSandboxCreateRoute
  '/_authenticated/instances/vm/$instanceId': typeof AuthenticatedInstancesVmInstanceIdRouteWithChildren
  '/_authenticated/instances/vm/create': typeof AuthenticatedInstancesVmCreateRoute
  '/_authenticated/networks/load-balancers/$loadBalancerId': typeof AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute
  '/_authenticated/networks/routes/$routeId': typeof AuthenticatedNetworksRoutesRouteIdRoute
  '/_authenticated/networks/security-groups/$securityGroupId': typeof AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute
  '/_authenticated/networks/subnets/$subnetId': typeof AuthenticatedNetworksSubnetsSubnetIdRoute
  '/_authenticated/networks/vpcs/$vpcId': typeof AuthenticatedNetworksVpcsVpcIdRoute
  '/_authenticated/objects/$bucketId/$objectId': typeof AuthenticatedObjectsBucketIdObjectIdRoute
  '/_authenticated/networks/load-balancers/': typeof AuthenticatedNetworksLoadBalancersIndexRoute
  '/_authenticated/networks/routes/': typeof AuthenticatedNetworksRoutesIndexRoute
  '/_authenticated/networks/security-groups/': typeof AuthenticatedNetworksSecurityGroupsIndexRoute
  '/_authenticated/networks/subnets/': typeof AuthenticatedNetworksSubnetsIndexRoute
  '/_authenticated/networks/vpcs/': typeof AuthenticatedNetworksVpcsIndexRoute
  '/_authenticated/objects/$bucketId/': typeof AuthenticatedObjectsBucketIdIndexRoute
  '/_authenticated/instances/vm/$instanceId/volumes/$volumeId': typeof AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/login/callback'
    | '/'
    | '/login/'
    | '/compute/overview'
    | '/filesystems/$filesystemId'
    | '/inference/$serviceId'
    | '/inference/policies'
    | '/instance-operations/$operationId'
    | '/instances/$instanceId'
    | '/instances/container'
    | '/instances/sandbox'
    | '/instances/vm'
    | '/k8s-clusters/$clusterId'
    | '/kb/$kbId'
    | '/models/$modelId'
    | '/objects/$bucketId'
    | '/vector-stores/$vectorStoreId'
    | '/volumes/$volumeId'
    | '/instances/console/$instanceId'
    | '/instances/terminal/$instanceId'
    | '/filesystems'
    | '/gpu-instances'
    | '/gpu-inventory'
    | '/images'
    | '/inference'
    | '/instances'
    | '/k8s-clusters'
    | '/kb'
    | '/models'
    | '/objects'
    | '/registry'
    | '/sandbox-templates'
    | '/vector-stores'
    | '/volumes'
    | '/instances/container/create'
    | '/inference/policies/$policyId'
    | '/instances/$instanceId/operations'
    | '/instances/container/$instanceId'
    | '/instances/sandbox/$instanceId'
    | '/instances/sandbox/create'
    | '/instances/vm/$instanceId'
    | '/instances/vm/create'
    | '/networks/load-balancers/$loadBalancerId'
    | '/networks/routes/$routeId'
    | '/networks/security-groups/$securityGroupId'
    | '/networks/subnets/$subnetId'
    | '/networks/vpcs/$vpcId'
    | '/objects/$bucketId/$objectId'
    | '/networks/load-balancers'
    | '/networks/routes'
    | '/networks/security-groups'
    | '/networks/subnets'
    | '/networks/vpcs'
    | '/objects/$bucketId/'
    | '/instances/vm/$instanceId/volumes/$volumeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login/callback'
    | '/'
    | '/login'
    | '/compute/overview'
    | '/filesystems/$filesystemId'
    | '/inference/$serviceId'
    | '/inference/policies'
    | '/instance-operations/$operationId'
    | '/instances/$instanceId'
    | '/instances/container'
    | '/instances/sandbox'
    | '/instances/vm'
    | '/k8s-clusters/$clusterId'
    | '/kb/$kbId'
    | '/models/$modelId'
    | '/vector-stores/$vectorStoreId'
    | '/volumes/$volumeId'
    | '/instances/console/$instanceId'
    | '/instances/terminal/$instanceId'
    | '/filesystems'
    | '/gpu-instances'
    | '/gpu-inventory'
    | '/images'
    | '/inference'
    | '/instances'
    | '/k8s-clusters'
    | '/kb'
    | '/models'
    | '/objects'
    | '/registry'
    | '/sandbox-templates'
    | '/vector-stores'
    | '/volumes'
    | '/instances/container/create'
    | '/inference/policies/$policyId'
    | '/instances/$instanceId/operations'
    | '/instances/container/$instanceId'
    | '/instances/sandbox/$instanceId'
    | '/instances/sandbox/create'
    | '/instances/vm/$instanceId'
    | '/instances/vm/create'
    | '/networks/load-balancers/$loadBalancerId'
    | '/networks/routes/$routeId'
    | '/networks/security-groups/$securityGroupId'
    | '/networks/subnets/$subnetId'
    | '/networks/vpcs/$vpcId'
    | '/objects/$bucketId/$objectId'
    | '/networks/load-balancers'
    | '/networks/routes'
    | '/networks/security-groups'
    | '/networks/subnets'
    | '/networks/vpcs'
    | '/objects/$bucketId'
    | '/instances/vm/$instanceId/volumes/$volumeId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/login/callback'
    | '/_authenticated/'
    | '/login/'
    | '/_authenticated/compute/overview'
    | '/_authenticated/filesystems/$filesystemId'
    | '/_authenticated/inference/$serviceId'
    | '/_authenticated/inference/policies'
    | '/_authenticated/instance-operations/$operationId'
    | '/_authenticated/instances/$instanceId'
    | '/_authenticated/instances/container'
    | '/_authenticated/instances/sandbox'
    | '/_authenticated/instances/vm'
    | '/_authenticated/k8s-clusters/$clusterId'
    | '/_authenticated/kb/$kbId'
    | '/_authenticated/models/$modelId'
    | '/_authenticated/objects/$bucketId'
    | '/_authenticated/vector-stores/$vectorStoreId'
    | '/_authenticated/volumes/$volumeId'
    | '/instances/console/$instanceId'
    | '/instances/terminal/$instanceId'
    | '/_authenticated/filesystems/'
    | '/_authenticated/gpu-instances/'
    | '/_authenticated/gpu-inventory/'
    | '/_authenticated/images/'
    | '/_authenticated/inference/'
    | '/_authenticated/instances/'
    | '/_authenticated/k8s-clusters/'
    | '/_authenticated/kb/'
    | '/_authenticated/models/'
    | '/_authenticated/objects/'
    | '/_authenticated/registry/'
    | '/_authenticated/sandbox-templates/'
    | '/_authenticated/vector-stores/'
    | '/_authenticated/volumes/'
    | '/_authenticated/instances/container/create'
    | '/_authenticated/inference/policies/$policyId'
    | '/_authenticated/instances/$instanceId/operations'
    | '/_authenticated/instances/container/$instanceId'
    | '/_authenticated/instances/sandbox/$instanceId'
    | '/_authenticated/instances/sandbox/create'
    | '/_authenticated/instances/vm/$instanceId'
    | '/_authenticated/instances/vm/create'
    | '/_authenticated/networks/load-balancers/$loadBalancerId'
    | '/_authenticated/networks/routes/$routeId'
    | '/_authenticated/networks/security-groups/$securityGroupId'
    | '/_authenticated/networks/subnets/$subnetId'
    | '/_authenticated/networks/vpcs/$vpcId'
    | '/_authenticated/objects/$bucketId/$objectId'
    | '/_authenticated/networks/load-balancers/'
    | '/_authenticated/networks/routes/'
    | '/_authenticated/networks/security-groups/'
    | '/_authenticated/networks/subnets/'
    | '/_authenticated/networks/vpcs/'
    | '/_authenticated/objects/$bucketId/'
    | '/_authenticated/instances/vm/$instanceId/volumes/$volumeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  InstancesConsoleInstanceIdRoute: typeof InstancesConsoleInstanceIdRoute
  InstancesTerminalInstanceIdRoute: typeof InstancesTerminalInstanceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/volumes/': {
      id: '/_authenticated/volumes/'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof AuthenticatedVolumesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vector-stores/': {
      id: '/_authenticated/vector-stores/'
      path: '/vector-stores'
      fullPath: '/vector-stores'
      preLoaderRoute: typeof AuthenticatedVectorStoresIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandbox-templates/': {
      id: '/_authenticated/sandbox-templates/'
      path: '/sandbox-templates'
      fullPath: '/sandbox-templates'
      preLoaderRoute: typeof AuthenticatedSandboxTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registry/': {
      id: '/_authenticated/registry/'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof AuthenticatedRegistryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objects/': {
      id: '/_authenticated/objects/'
      path: '/objects'
      fullPath: '/objects'
      preLoaderRoute: typeof AuthenticatedObjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models/': {
      id: '/_authenticated/models/'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kb/': {
      id: '/_authenticated/kb/'
      path: '/kb'
      fullPath: '/kb'
      preLoaderRoute: typeof AuthenticatedKbIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/k8s-clusters/': {
      id: '/_authenticated/k8s-clusters/'
      path: '/k8s-clusters'
      fullPath: '/k8s-clusters'
      preLoaderRoute: typeof AuthenticatedK8sClustersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/': {
      id: '/_authenticated/instances/'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof AuthenticatedInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inference/': {
      id: '/_authenticated/inference/'
      path: '/inference'
      fullPath: '/inference'
      preLoaderRoute: typeof AuthenticatedInferenceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/images/': {
      id: '/_authenticated/images/'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AuthenticatedImagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gpu-inventory/': {
      id: '/_authenticated/gpu-inventory/'
      path: '/gpu-inventory'
      fullPath: '/gpu-inventory'
      preLoaderRoute: typeof AuthenticatedGpuInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gpu-instances/': {
      id: '/_authenticated/gpu-instances/'
      path: '/gpu-instances'
      fullPath: '/gpu-instances'
      preLoaderRoute: typeof AuthenticatedGpuInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/filesystems/': {
      id: '/_authenticated/filesystems/'
      path: '/filesystems'
      fullPath: '/filesystems'
      preLoaderRoute: typeof AuthenticatedFilesystemsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/instances/terminal/$instanceId': {
      id: '/instances/terminal/$instanceId'
      path: '/instances/terminal/$instanceId'
      fullPath: '/instances/terminal/$instanceId'
      preLoaderRoute: typeof InstancesTerminalInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/console/$instanceId': {
      id: '/instances/console/$instanceId'
      path: '/instances/console/$instanceId'
      fullPath: '/instances/console/$instanceId'
      preLoaderRoute: typeof InstancesConsoleInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/volumes/$volumeId': {
      id: '/_authenticated/volumes/$volumeId'
      path: '/volumes/$volumeId'
      fullPath: '/volumes/$volumeId'
      preLoaderRoute: typeof AuthenticatedVolumesVolumeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vector-stores/$vectorStoreId': {
      id: '/_authenticated/vector-stores/$vectorStoreId'
      path: '/vector-stores/$vectorStoreId'
      fullPath: '/vector-stores/$vectorStoreId'
      preLoaderRoute: typeof AuthenticatedVectorStoresVectorStoreIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objects/$bucketId': {
      id: '/_authenticated/objects/$bucketId'
      path: '/objects/$bucketId'
      fullPath: '/objects/$bucketId'
      preLoaderRoute: typeof AuthenticatedObjectsBucketIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models/$modelId': {
      id: '/_authenticated/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof AuthenticatedModelsModelIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kb/$kbId': {
      id: '/_authenticated/kb/$kbId'
      path: '/kb/$kbId'
      fullPath: '/kb/$kbId'
      preLoaderRoute: typeof AuthenticatedKbKbIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/k8s-clusters/$clusterId': {
      id: '/_authenticated/k8s-clusters/$clusterId'
      path: '/k8s-clusters/$clusterId'
      fullPath: '/k8s-clusters/$clusterId'
      preLoaderRoute: typeof AuthenticatedK8sClustersClusterIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/vm': {
      id: '/_authenticated/instances/vm'
      path: '/instances/vm'
      fullPath: '/instances/vm'
      preLoaderRoute: typeof AuthenticatedInstancesVmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/sandbox': {
      id: '/_authenticated/instances/sandbox'
      path: '/instances/sandbox'
      fullPath: '/instances/sandbox'
      preLoaderRoute: typeof AuthenticatedInstancesSandboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/container': {
      id: '/_authenticated/instances/container'
      path: '/instances/container'
      fullPath: '/instances/container'
      preLoaderRoute: typeof AuthenticatedInstancesContainerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/$instanceId': {
      id: '/_authenticated/instances/$instanceId'
      path: '/instances/$instanceId'
      fullPath: '/instances/$instanceId'
      preLoaderRoute: typeof AuthenticatedInstancesInstanceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instance-operations/$operationId': {
      id: '/_authenticated/instance-operations/$operationId'
      path: '/instance-operations/$operationId'
      fullPath: '/instance-operations/$operationId'
      preLoaderRoute: typeof AuthenticatedInstanceOperationsOperationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inference/policies': {
      id: '/_authenticated/inference/policies'
      path: '/inference/policies'
      fullPath: '/inference/policies'
      preLoaderRoute: typeof AuthenticatedInferencePoliciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inference/$serviceId': {
      id: '/_authenticated/inference/$serviceId'
      path: '/inference/$serviceId'
      fullPath: '/inference/$serviceId'
      preLoaderRoute: typeof AuthenticatedInferenceServiceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/filesystems/$filesystemId': {
      id: '/_authenticated/filesystems/$filesystemId'
      path: '/filesystems/$filesystemId'
      fullPath: '/filesystems/$filesystemId'
      preLoaderRoute: typeof AuthenticatedFilesystemsFilesystemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compute/overview': {
      id: '/_authenticated/compute/overview'
      path: '/compute/overview'
      fullPath: '/compute/overview'
      preLoaderRoute: typeof AuthenticatedComputeOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objects/$bucketId/': {
      id: '/_authenticated/objects/$bucketId/'
      path: '/'
      fullPath: '/objects/$bucketId/'
      preLoaderRoute: typeof AuthenticatedObjectsBucketIdIndexRouteImport
      parentRoute: typeof AuthenticatedObjectsBucketIdRoute
    }
    '/_authenticated/networks/vpcs/': {
      id: '/_authenticated/networks/vpcs/'
      path: '/networks/vpcs'
      fullPath: '/networks/vpcs'
      preLoaderRoute: typeof AuthenticatedNetworksVpcsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/subnets/': {
      id: '/_authenticated/networks/subnets/'
      path: '/networks/subnets'
      fullPath: '/networks/subnets'
      preLoaderRoute: typeof AuthenticatedNetworksSubnetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/security-groups/': {
      id: '/_authenticated/networks/security-groups/'
      path: '/networks/security-groups'
      fullPath: '/networks/security-groups'
      preLoaderRoute: typeof AuthenticatedNetworksSecurityGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/routes/': {
      id: '/_authenticated/networks/routes/'
      path: '/networks/routes'
      fullPath: '/networks/routes'
      preLoaderRoute: typeof AuthenticatedNetworksRoutesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/load-balancers/': {
      id: '/_authenticated/networks/load-balancers/'
      path: '/networks/load-balancers'
      fullPath: '/networks/load-balancers'
      preLoaderRoute: typeof AuthenticatedNetworksLoadBalancersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objects/$bucketId/$objectId': {
      id: '/_authenticated/objects/$bucketId/$objectId'
      path: '/$objectId'
      fullPath: '/objects/$bucketId/$objectId'
      preLoaderRoute: typeof AuthenticatedObjectsBucketIdObjectIdRouteImport
      parentRoute: typeof AuthenticatedObjectsBucketIdRoute
    }
    '/_authenticated/networks/vpcs/$vpcId': {
      id: '/_authenticated/networks/vpcs/$vpcId'
      path: '/networks/vpcs/$vpcId'
      fullPath: '/networks/vpcs/$vpcId'
      preLoaderRoute: typeof AuthenticatedNetworksVpcsVpcIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/subnets/$subnetId': {
      id: '/_authenticated/networks/subnets/$subnetId'
      path: '/networks/subnets/$subnetId'
      fullPath: '/networks/subnets/$subnetId'
      preLoaderRoute: typeof AuthenticatedNetworksSubnetsSubnetIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/security-groups/$securityGroupId': {
      id: '/_authenticated/networks/security-groups/$securityGroupId'
      path: '/networks/security-groups/$securityGroupId'
      fullPath: '/networks/security-groups/$securityGroupId'
      preLoaderRoute: typeof AuthenticatedNetworksSecurityGroupsSecurityGroupIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/routes/$routeId': {
      id: '/_authenticated/networks/routes/$routeId'
      path: '/networks/routes/$routeId'
      fullPath: '/networks/routes/$routeId'
      preLoaderRoute: typeof AuthenticatedNetworksRoutesRouteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/load-balancers/$loadBalancerId': {
      id: '/_authenticated/networks/load-balancers/$loadBalancerId'
      path: '/networks/load-balancers/$loadBalancerId'
      fullPath: '/networks/load-balancers/$loadBalancerId'
      preLoaderRoute: typeof AuthenticatedNetworksLoadBalancersLoadBalancerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/vm/create': {
      id: '/_authenticated/instances/vm/create'
      path: '/create'
      fullPath: '/instances/vm/create'
      preLoaderRoute: typeof AuthenticatedInstancesVmCreateRouteImport
      parentRoute: typeof AuthenticatedInstancesVmRoute
    }
    '/_authenticated/instances/vm/$instanceId': {
      id: '/_authenticated/instances/vm/$instanceId'
      path: '/$instanceId'
      fullPath: '/instances/vm/$instanceId'
      preLoaderRoute: typeof AuthenticatedInstancesVmInstanceIdRouteImport
      parentRoute: typeof AuthenticatedInstancesVmRoute
    }
    '/_authenticated/instances/sandbox/create': {
      id: '/_authenticated/instances/sandbox/create'
      path: '/create'
      fullPath: '/instances/sandbox/create'
      preLoaderRoute: typeof AuthenticatedInstancesSandboxCreateRouteImport
      parentRoute: typeof AuthenticatedInstancesSandboxRoute
    }
    '/_authenticated/instances/sandbox/$instanceId': {
      id: '/_authenticated/instances/sandbox/$instanceId'
      path: '/$instanceId'
      fullPath: '/instances/sandbox/$instanceId'
      preLoaderRoute: typeof AuthenticatedInstancesSandboxInstanceIdRouteImport
      parentRoute: typeof AuthenticatedInstancesSandboxRoute
    }
    '/_authenticated/instances/container/$instanceId': {
      id: '/_authenticated/instances/container/$instanceId'
      path: '/$instanceId'
      fullPath: '/instances/container/$instanceId'
      preLoaderRoute: typeof AuthenticatedInstancesContainerInstanceIdRouteImport
      parentRoute: typeof AuthenticatedInstancesContainerRoute
    }
    '/_authenticated/instances/$instanceId/operations': {
      id: '/_authenticated/instances/$instanceId/operations'
      path: '/operations'
      fullPath: '/instances/$instanceId/operations'
      preLoaderRoute: typeof AuthenticatedInstancesInstanceIdOperationsRouteImport
      parentRoute: typeof AuthenticatedInstancesInstanceIdRoute
    }
    '/_authenticated/inference/policies/$policyId': {
      id: '/_authenticated/inference/policies/$policyId'
      path: '/$policyId'
      fullPath: '/inference/policies/$policyId'
      preLoaderRoute: typeof AuthenticatedInferencePoliciesPolicyIdRouteImport
      parentRoute: typeof AuthenticatedInferencePoliciesRoute
    }
    '/_authenticated/instances/container/create': {
      id: '/_authenticated/instances/container/create'
      path: '/create'
      fullPath: '/instances/container/create'
      preLoaderRoute: typeof AuthenticatedInstancesContainerCreateRouteRouteImport
      parentRoute: typeof AuthenticatedInstancesContainerRoute
    }
    '/_authenticated/instances/vm/$instanceId/volumes/$volumeId': {
      id: '/_authenticated/instances/vm/$instanceId/volumes/$volumeId'
      path: '/volumes/$volumeId'
      fullPath: '/instances/vm/$instanceId/volumes/$volumeId'
      preLoaderRoute: typeof AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRouteImport
      parentRoute: typeof AuthenticatedInstancesVmInstanceIdRoute
    }
  }
}

interface AuthenticatedInferencePoliciesRouteChildren {
  AuthenticatedInferencePoliciesPolicyIdRoute: typeof AuthenticatedInferencePoliciesPolicyIdRoute
}

const AuthenticatedInferencePoliciesRouteChildren: AuthenticatedInferencePoliciesRouteChildren =
  {
    AuthenticatedInferencePoliciesPolicyIdRoute:
      AuthenticatedInferencePoliciesPolicyIdRoute,
  }

const AuthenticatedInferencePoliciesRouteWithChildren =
  AuthenticatedInferencePoliciesRoute._addFileChildren(
    AuthenticatedInferencePoliciesRouteChildren,
  )

interface AuthenticatedInstancesInstanceIdRouteChildren {
  AuthenticatedInstancesInstanceIdOperationsRoute: typeof AuthenticatedInstancesInstanceIdOperationsRoute
}

const AuthenticatedInstancesInstanceIdRouteChildren: AuthenticatedInstancesInstanceIdRouteChildren =
  {
    AuthenticatedInstancesInstanceIdOperationsRoute:
      AuthenticatedInstancesInstanceIdOperationsRoute,
  }

const AuthenticatedInstancesInstanceIdRouteWithChildren =
  AuthenticatedInstancesInstanceIdRoute._addFileChildren(
    AuthenticatedInstancesInstanceIdRouteChildren,
  )

interface AuthenticatedInstancesContainerRouteChildren {
  AuthenticatedInstancesContainerCreateRouteRoute: typeof AuthenticatedInstancesContainerCreateRouteRoute
  AuthenticatedInstancesContainerInstanceIdRoute: typeof AuthenticatedInstancesContainerInstanceIdRoute
}

const AuthenticatedInstancesContainerRouteChildren: AuthenticatedInstancesContainerRouteChildren =
  {
    AuthenticatedInstancesContainerCreateRouteRoute:
      AuthenticatedInstancesContainerCreateRouteRoute,
    AuthenticatedInstancesContainerInstanceIdRoute:
      AuthenticatedInstancesContainerInstanceIdRoute,
  }

const AuthenticatedInstancesContainerRouteWithChildren =
  AuthenticatedInstancesContainerRoute._addFileChildren(
    AuthenticatedInstancesContainerRouteChildren,
  )

interface AuthenticatedInstancesSandboxRouteChildren {
  AuthenticatedInstancesSandboxInstanceIdRoute: typeof AuthenticatedInstancesSandboxInstanceIdRoute
  AuthenticatedInstancesSandboxCreateRoute: typeof AuthenticatedInstancesSandboxCreateRoute
}

const AuthenticatedInstancesSandboxRouteChildren: AuthenticatedInstancesSandboxRouteChildren =
  {
    AuthenticatedInstancesSandboxInstanceIdRoute:
      AuthenticatedInstancesSandboxInstanceIdRoute,
    AuthenticatedInstancesSandboxCreateRoute:
      AuthenticatedInstancesSandboxCreateRoute,
  }

const AuthenticatedInstancesSandboxRouteWithChildren =
  AuthenticatedInstancesSandboxRoute._addFileChildren(
    AuthenticatedInstancesSandboxRouteChildren,
  )

interface AuthenticatedInstancesVmInstanceIdRouteChildren {
  AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute: typeof AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute
}

const AuthenticatedInstancesVmInstanceIdRouteChildren: AuthenticatedInstancesVmInstanceIdRouteChildren =
  {
    AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute:
      AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute,
  }

const AuthenticatedInstancesVmInstanceIdRouteWithChildren =
  AuthenticatedInstancesVmInstanceIdRoute._addFileChildren(
    AuthenticatedInstancesVmInstanceIdRouteChildren,
  )

interface AuthenticatedInstancesVmRouteChildren {
  AuthenticatedInstancesVmInstanceIdRoute: typeof AuthenticatedInstancesVmInstanceIdRouteWithChildren
  AuthenticatedInstancesVmCreateRoute: typeof AuthenticatedInstancesVmCreateRoute
}

const AuthenticatedInstancesVmRouteChildren: AuthenticatedInstancesVmRouteChildren =
  {
    AuthenticatedInstancesVmInstanceIdRoute:
      AuthenticatedInstancesVmInstanceIdRouteWithChildren,
    AuthenticatedInstancesVmCreateRoute: AuthenticatedInstancesVmCreateRoute,
  }

const AuthenticatedInstancesVmRouteWithChildren =
  AuthenticatedInstancesVmRoute._addFileChildren(
    AuthenticatedInstancesVmRouteChildren,
  )

interface AuthenticatedObjectsBucketIdRouteChildren {
  AuthenticatedObjectsBucketIdObjectIdRoute: typeof AuthenticatedObjectsBucketIdObjectIdRoute
  AuthenticatedObjectsBucketIdIndexRoute: typeof AuthenticatedObjectsBucketIdIndexRoute
}

const AuthenticatedObjectsBucketIdRouteChildren: AuthenticatedObjectsBucketIdRouteChildren =
  {
    AuthenticatedObjectsBucketIdObjectIdRoute:
      AuthenticatedObjectsBucketIdObjectIdRoute,
    AuthenticatedObjectsBucketIdIndexRoute:
      AuthenticatedObjectsBucketIdIndexRoute,
  }

const AuthenticatedObjectsBucketIdRouteWithChildren =
  AuthenticatedObjectsBucketIdRoute._addFileChildren(
    AuthenticatedObjectsBucketIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedComputeOverviewRoute: typeof AuthenticatedComputeOverviewRoute
  AuthenticatedFilesystemsFilesystemIdRoute: typeof AuthenticatedFilesystemsFilesystemIdRoute
  AuthenticatedInferenceServiceIdRoute: typeof AuthenticatedInferenceServiceIdRoute
  AuthenticatedInferencePoliciesRoute: typeof AuthenticatedInferencePoliciesRouteWithChildren
  AuthenticatedInstanceOperationsOperationIdRoute: typeof AuthenticatedInstanceOperationsOperationIdRoute
  AuthenticatedInstancesInstanceIdRoute: typeof AuthenticatedInstancesInstanceIdRouteWithChildren
  AuthenticatedInstancesContainerRoute: typeof AuthenticatedInstancesContainerRouteWithChildren
  AuthenticatedInstancesSandboxRoute: typeof AuthenticatedInstancesSandboxRouteWithChildren
  AuthenticatedInstancesVmRoute: typeof AuthenticatedInstancesVmRouteWithChildren
  AuthenticatedK8sClustersClusterIdRoute: typeof AuthenticatedK8sClustersClusterIdRoute
  AuthenticatedKbKbIdRoute: typeof AuthenticatedKbKbIdRoute
  AuthenticatedModelsModelIdRoute: typeof AuthenticatedModelsModelIdRoute
  AuthenticatedObjectsBucketIdRoute: typeof AuthenticatedObjectsBucketIdRouteWithChildren
  AuthenticatedVectorStoresVectorStoreIdRoute: typeof AuthenticatedVectorStoresVectorStoreIdRoute
  AuthenticatedVolumesVolumeIdRoute: typeof AuthenticatedVolumesVolumeIdRoute
  AuthenticatedFilesystemsIndexRoute: typeof AuthenticatedFilesystemsIndexRoute
  AuthenticatedGpuInstancesIndexRoute: typeof AuthenticatedGpuInstancesIndexRoute
  AuthenticatedGpuInventoryIndexRoute: typeof AuthenticatedGpuInventoryIndexRoute
  AuthenticatedImagesIndexRoute: typeof AuthenticatedImagesIndexRoute
  AuthenticatedInferenceIndexRoute: typeof AuthenticatedInferenceIndexRoute
  AuthenticatedInstancesIndexRoute: typeof AuthenticatedInstancesIndexRoute
  AuthenticatedK8sClustersIndexRoute: typeof AuthenticatedK8sClustersIndexRoute
  AuthenticatedKbIndexRoute: typeof AuthenticatedKbIndexRoute
  AuthenticatedModelsIndexRoute: typeof AuthenticatedModelsIndexRoute
  AuthenticatedObjectsIndexRoute: typeof AuthenticatedObjectsIndexRoute
  AuthenticatedRegistryIndexRoute: typeof AuthenticatedRegistryIndexRoute
  AuthenticatedSandboxTemplatesIndexRoute: typeof AuthenticatedSandboxTemplatesIndexRoute
  AuthenticatedVectorStoresIndexRoute: typeof AuthenticatedVectorStoresIndexRoute
  AuthenticatedVolumesIndexRoute: typeof AuthenticatedVolumesIndexRoute
  AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute: typeof AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute
  AuthenticatedNetworksRoutesRouteIdRoute: typeof AuthenticatedNetworksRoutesRouteIdRoute
  AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute: typeof AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute
  AuthenticatedNetworksSubnetsSubnetIdRoute: typeof AuthenticatedNetworksSubnetsSubnetIdRoute
  AuthenticatedNetworksVpcsVpcIdRoute: typeof AuthenticatedNetworksVpcsVpcIdRoute
  AuthenticatedNetworksLoadBalancersIndexRoute: typeof AuthenticatedNetworksLoadBalancersIndexRoute
  AuthenticatedNetworksRoutesIndexRoute: typeof AuthenticatedNetworksRoutesIndexRoute
  AuthenticatedNetworksSecurityGroupsIndexRoute: typeof AuthenticatedNetworksSecurityGroupsIndexRoute
  AuthenticatedNetworksSubnetsIndexRoute: typeof AuthenticatedNetworksSubnetsIndexRoute
  AuthenticatedNetworksVpcsIndexRoute: typeof AuthenticatedNetworksVpcsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedComputeOverviewRoute: AuthenticatedComputeOverviewRoute,
  AuthenticatedFilesystemsFilesystemIdRoute:
    AuthenticatedFilesystemsFilesystemIdRoute,
  AuthenticatedInferenceServiceIdRoute: AuthenticatedInferenceServiceIdRoute,
  AuthenticatedInferencePoliciesRoute:
    AuthenticatedInferencePoliciesRouteWithChildren,
  AuthenticatedInstanceOperationsOperationIdRoute:
    AuthenticatedInstanceOperationsOperationIdRoute,
  AuthenticatedInstancesInstanceIdRoute:
    AuthenticatedInstancesInstanceIdRouteWithChildren,
  AuthenticatedInstancesContainerRoute:
    AuthenticatedInstancesContainerRouteWithChildren,
  AuthenticatedInstancesSandboxRoute:
    AuthenticatedInstancesSandboxRouteWithChildren,
  AuthenticatedInstancesVmRoute: AuthenticatedInstancesVmRouteWithChildren,
  AuthenticatedK8sClustersClusterIdRoute:
    AuthenticatedK8sClustersClusterIdRoute,
  AuthenticatedKbKbIdRoute: AuthenticatedKbKbIdRoute,
  AuthenticatedModelsModelIdRoute: AuthenticatedModelsModelIdRoute,
  AuthenticatedObjectsBucketIdRoute:
    AuthenticatedObjectsBucketIdRouteWithChildren,
  AuthenticatedVectorStoresVectorStoreIdRoute:
    AuthenticatedVectorStoresVectorStoreIdRoute,
  AuthenticatedVolumesVolumeIdRoute: AuthenticatedVolumesVolumeIdRoute,
  AuthenticatedFilesystemsIndexRoute: AuthenticatedFilesystemsIndexRoute,
  AuthenticatedGpuInstancesIndexRoute: AuthenticatedGpuInstancesIndexRoute,
  AuthenticatedGpuInventoryIndexRoute: AuthenticatedGpuInventoryIndexRoute,
  AuthenticatedImagesIndexRoute: AuthenticatedImagesIndexRoute,
  AuthenticatedInferenceIndexRoute: AuthenticatedInferenceIndexRoute,
  AuthenticatedInstancesIndexRoute: AuthenticatedInstancesIndexRoute,
  AuthenticatedK8sClustersIndexRoute: AuthenticatedK8sClustersIndexRoute,
  AuthenticatedKbIndexRoute: AuthenticatedKbIndexRoute,
  AuthenticatedModelsIndexRoute: AuthenticatedModelsIndexRoute,
  AuthenticatedObjectsIndexRoute: AuthenticatedObjectsIndexRoute,
  AuthenticatedRegistryIndexRoute: AuthenticatedRegistryIndexRoute,
  AuthenticatedSandboxTemplatesIndexRoute:
    AuthenticatedSandboxTemplatesIndexRoute,
  AuthenticatedVectorStoresIndexRoute: AuthenticatedVectorStoresIndexRoute,
  AuthenticatedVolumesIndexRoute: AuthenticatedVolumesIndexRoute,
  AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute:
    AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute,
  AuthenticatedNetworksRoutesRouteIdRoute:
    AuthenticatedNetworksRoutesRouteIdRoute,
  AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute:
    AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute,
  AuthenticatedNetworksSubnetsSubnetIdRoute:
    AuthenticatedNetworksSubnetsSubnetIdRoute,
  AuthenticatedNetworksVpcsVpcIdRoute: AuthenticatedNetworksVpcsVpcIdRoute,
  AuthenticatedNetworksLoadBalancersIndexRoute:
    AuthenticatedNetworksLoadBalancersIndexRoute,
  AuthenticatedNetworksRoutesIndexRoute: AuthenticatedNetworksRoutesIndexRoute,
  AuthenticatedNetworksSecurityGroupsIndexRoute:
    AuthenticatedNetworksSecurityGroupsIndexRoute,
  AuthenticatedNetworksSubnetsIndexRoute:
    AuthenticatedNetworksSubnetsIndexRoute,
  AuthenticatedNetworksVpcsIndexRoute: AuthenticatedNetworksVpcsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginCallbackRoute: typeof LoginCallbackRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginCallbackRoute: LoginCallbackRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  InstancesConsoleInstanceIdRoute: InstancesConsoleInstanceIdRoute,
  InstancesTerminalInstanceIdRoute: InstancesTerminalInstanceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
