/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LoginCallbackRouteImport } from './routes/login.callback'
import { Route as AuthenticatedVolumesIndexRouteImport } from './routes/_authenticated/volumes/index'
import { Route as AuthenticatedVectorStoresIndexRouteImport } from './routes/_authenticated/vector-stores/index'
import { Route as AuthenticatedUsageIndexRouteImport } from './routes/_authenticated/usage/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSecretsIndexRouteImport } from './routes/_authenticated/secrets/index'
import { Route as AuthenticatedSandboxTemplatesIndexRouteImport } from './routes/_authenticated/sandbox-templates/index'
import { Route as AuthenticatedRegistryIndexRouteImport } from './routes/_authenticated/registry/index'
import { Route as AuthenticatedObservabilityIndexRouteImport } from './routes/_authenticated/observability/index'
import { Route as AuthenticatedObjectsIndexRouteImport } from './routes/_authenticated/objects/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedK8sClustersIndexRouteImport } from './routes/_authenticated/k8s-clusters/index'
import { Route as AuthenticatedInstancesIndexRouteImport } from './routes/_authenticated/instances/index'
import { Route as AuthenticatedImagesIndexRouteImport } from './routes/_authenticated/images/index'
import { Route as AuthenticatedGpuInventoryIndexRouteImport } from './routes/_authenticated/gpu-inventory/index'
import { Route as AuthenticatedFilesystemsIndexRouteImport } from './routes/_authenticated/filesystems/index'
import { Route as AuthenticatedEncryptionIndexRouteImport } from './routes/_authenticated/encryption/index'
import { Route as AuthenticatedBareMetalIndexRouteImport } from './routes/_authenticated/bare-metal/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as InstancesTerminalInstanceIdRouteImport } from './routes/instances/terminal/$instanceId'
import { Route as InstancesConsoleInstanceIdRouteImport } from './routes/instances/console/$instanceId'
import { Route as AuthenticatedVolumesVolumeIdRouteImport } from './routes/_authenticated/volumes/$volumeId'
import { Route as AuthenticatedVectorStoresVectorStoreIdRouteImport } from './routes/_authenticated/vector-stores/$vectorStoreId'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings/api-keys'
import { Route as AuthenticatedSecretsSecretIdRouteImport } from './routes/_authenticated/secrets/$secretId'
import { Route as AuthenticatedObjectsBucketIdRouteImport } from './routes/_authenticated/objects/$bucketId'
import { Route as AuthenticatedK8sClustersClusterIdRouteImport } from './routes/_authenticated/k8s-clusters/$clusterId'
import { Route as AuthenticatedInstancesVmRouteImport } from './routes/_authenticated/instances/vm'
import { Route as AuthenticatedInstancesSandboxRouteImport } from './routes/_authenticated/instances/sandbox'
import { Route as AuthenticatedInstancesGpuRouteImport } from './routes/_authenticated/instances/gpu'
import { Route as AuthenticatedInstancesContainerRouteImport } from './routes/_authenticated/instances/container'
import { Route as AuthenticatedInstancesInstanceIdRouteImport } from './routes/_authenticated/instances/$instanceId'
import { Route as AuthenticatedInstanceOperationsOperationIdRouteImport } from './routes/_authenticated/instance-operations/$operationId'
import { Route as AuthenticatedFilesystemsFilesystemIdRouteImport } from './routes/_authenticated/filesystems/$filesystemId'
import { Route as AuthenticatedDemoLeafRouteImport } from './routes/_authenticated/demo/leaf'
import { Route as AuthenticatedDemoBI2RouteImport } from './routes/_authenticated/demo/b-i-2'
import { Route as AuthenticatedDemoBI1RouteImport } from './routes/_authenticated/demo/b-i-1'
import { Route as AuthenticatedDemoB1RouteImport } from './routes/_authenticated/demo/b-1'
import { Route as AuthenticatedDemoA2RouteImport } from './routes/_authenticated/demo/a-2'
import { Route as AuthenticatedDemoA1RouteImport } from './routes/_authenticated/demo/a-1'
import { Route as AuthenticatedObjectsBucketIdIndexRouteImport } from './routes/_authenticated/objects/$bucketId/index'
import { Route as AuthenticatedNetworksVpcsIndexRouteImport } from './routes/_authenticated/networks/vpcs/index'
import { Route as AuthenticatedNetworksSubnetsIndexRouteImport } from './routes/_authenticated/networks/subnets/index'
import { Route as AuthenticatedNetworksSecurityGroupsIndexRouteImport } from './routes/_authenticated/networks/security-groups/index'
import { Route as AuthenticatedNetworksRoutesIndexRouteImport } from './routes/_authenticated/networks/routes/index'
import { Route as AuthenticatedNetworksLoadBalancersIndexRouteImport } from './routes/_authenticated/networks/load-balancers/index'
import { Route as AuthenticatedObjectsBucketIdObjectIdRouteImport } from './routes/_authenticated/objects/$bucketId/$objectId'
import { Route as AuthenticatedNetworksVpcsVpcIdRouteImport } from './routes/_authenticated/networks/vpcs/$vpcId'
import { Route as AuthenticatedNetworksSubnetsSubnetIdRouteImport } from './routes/_authenticated/networks/subnets/$subnetId'
import { Route as AuthenticatedNetworksSecurityGroupsSecurityGroupIdRouteImport } from './routes/_authenticated/networks/security-groups/$securityGroupId'
import { Route as AuthenticatedNetworksRoutesRouteIdRouteImport } from './routes/_authenticated/networks/routes/$routeId'
import { Route as AuthenticatedNetworksLoadBalancersLoadBalancerIdRouteImport } from './routes/_authenticated/networks/load-balancers/$loadBalancerId'
import { Route as AuthenticatedInstancesVmCreateRouteImport } from './routes/_authenticated/instances/vm/create'
import { Route as AuthenticatedInstancesVmInstanceIdRouteImport } from './routes/_authenticated/instances/vm/$instanceId'
import { Route as AuthenticatedInstancesSandboxCreateRouteImport } from './routes/_authenticated/instances/sandbox/create'
import { Route as AuthenticatedInstancesSandboxInstanceIdRouteImport } from './routes/_authenticated/instances/sandbox/$instanceId'
import { Route as AuthenticatedInstancesGpuCreateRouteImport } from './routes/_authenticated/instances/gpu/create'
import { Route as AuthenticatedInstancesContainerInstanceIdRouteImport } from './routes/_authenticated/instances/container/$instanceId'
import { Route as AuthenticatedInstancesInstanceIdOperationsRouteImport } from './routes/_authenticated/instances/$instanceId.operations'
import { Route as AuthenticatedInstancesContainerCreateRouteRouteImport } from './routes/_authenticated/instances/container/create/route'
import { Route as AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRouteImport } from './routes/_authenticated/instances/vm/$instanceId/volumes/$volumeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedVolumesIndexRoute =
  AuthenticatedVolumesIndexRouteImport.update({
    id: '/volumes/',
    path: '/volumes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVectorStoresIndexRoute =
  AuthenticatedVectorStoresIndexRouteImport.update({
    id: '/vector-stores/',
    path: '/vector-stores/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsageIndexRoute = AuthenticatedUsageIndexRouteImport.update({
  id: '/usage/',
  path: '/usage/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSecretsIndexRoute =
  AuthenticatedSecretsIndexRouteImport.update({
    id: '/secrets/',
    path: '/secrets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxTemplatesIndexRoute =
  AuthenticatedSandboxTemplatesIndexRouteImport.update({
    id: '/sandbox-templates/',
    path: '/sandbox-templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistryIndexRoute =
  AuthenticatedRegistryIndexRouteImport.update({
    id: '/registry/',
    path: '/registry/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObservabilityIndexRoute =
  AuthenticatedObservabilityIndexRouteImport.update({
    id: '/observability/',
    path: '/observability/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObjectsIndexRoute =
  AuthenticatedObjectsIndexRouteImport.update({
    id: '/objects/',
    path: '/objects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedK8sClustersIndexRoute =
  AuthenticatedK8sClustersIndexRouteImport.update({
    id: '/k8s-clusters/',
    path: '/k8s-clusters/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesIndexRoute =
  AuthenticatedInstancesIndexRouteImport.update({
    id: '/instances/',
    path: '/instances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImagesIndexRoute =
  AuthenticatedImagesIndexRouteImport.update({
    id: '/images/',
    path: '/images/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGpuInventoryIndexRoute =
  AuthenticatedGpuInventoryIndexRouteImport.update({
    id: '/gpu-inventory/',
    path: '/gpu-inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilesystemsIndexRoute =
  AuthenticatedFilesystemsIndexRouteImport.update({
    id: '/filesystems/',
    path: '/filesystems/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEncryptionIndexRoute =
  AuthenticatedEncryptionIndexRouteImport.update({
    id: '/encryption/',
    path: '/encryption/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBareMetalIndexRoute =
  AuthenticatedBareMetalIndexRouteImport.update({
    id: '/bare-metal/',
    path: '/bare-metal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const InstancesTerminalInstanceIdRoute =
  InstancesTerminalInstanceIdRouteImport.update({
    id: '/instances/terminal/$instanceId',
    path: '/instances/terminal/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstancesConsoleInstanceIdRoute =
  InstancesConsoleInstanceIdRouteImport.update({
    id: '/instances/console/$instanceId',
    path: '/instances/console/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedVolumesVolumeIdRoute =
  AuthenticatedVolumesVolumeIdRouteImport.update({
    id: '/volumes/$volumeId',
    path: '/volumes/$volumeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVectorStoresVectorStoreIdRoute =
  AuthenticatedVectorStoresVectorStoreIdRouteImport.update({
    id: '/vector-stores/$vectorStoreId',
    path: '/vector-stores/$vectorStoreId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSecretsSecretIdRoute =
  AuthenticatedSecretsSecretIdRouteImport.update({
    id: '/secrets/$secretId',
    path: '/secrets/$secretId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObjectsBucketIdRoute =
  AuthenticatedObjectsBucketIdRouteImport.update({
    id: '/objects/$bucketId',
    path: '/objects/$bucketId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedK8sClustersClusterIdRoute =
  AuthenticatedK8sClustersClusterIdRouteImport.update({
    id: '/k8s-clusters/$clusterId',
    path: '/k8s-clusters/$clusterId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesVmRoute =
  AuthenticatedInstancesVmRouteImport.update({
    id: '/instances/vm',
    path: '/instances/vm',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesSandboxRoute =
  AuthenticatedInstancesSandboxRouteImport.update({
    id: '/instances/sandbox',
    path: '/instances/sandbox',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesGpuRoute =
  AuthenticatedInstancesGpuRouteImport.update({
    id: '/instances/gpu',
    path: '/instances/gpu',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesContainerRoute =
  AuthenticatedInstancesContainerRouteImport.update({
    id: '/instances/container',
    path: '/instances/container',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesInstanceIdRoute =
  AuthenticatedInstancesInstanceIdRouteImport.update({
    id: '/instances/$instanceId',
    path: '/instances/$instanceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstanceOperationsOperationIdRoute =
  AuthenticatedInstanceOperationsOperationIdRouteImport.update({
    id: '/instance-operations/$operationId',
    path: '/instance-operations/$operationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilesystemsFilesystemIdRoute =
  AuthenticatedFilesystemsFilesystemIdRouteImport.update({
    id: '/filesystems/$filesystemId',
    path: '/filesystems/$filesystemId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemoLeafRoute = AuthenticatedDemoLeafRouteImport.update({
  id: '/demo/leaf',
  path: '/demo/leaf',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemoBI2Route = AuthenticatedDemoBI2RouteImport.update({
  id: '/demo/b-i-2',
  path: '/demo/b-i-2',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemoBI1Route = AuthenticatedDemoBI1RouteImport.update({
  id: '/demo/b-i-1',
  path: '/demo/b-i-1',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemoB1Route = AuthenticatedDemoB1RouteImport.update({
  id: '/demo/b-1',
  path: '/demo/b-1',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemoA2Route = AuthenticatedDemoA2RouteImport.update({
  id: '/demo/a-2',
  path: '/demo/a-2',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemoA1Route = AuthenticatedDemoA1RouteImport.update({
  id: '/demo/a-1',
  path: '/demo/a-1',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedObjectsBucketIdIndexRoute =
  AuthenticatedObjectsBucketIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedObjectsBucketIdRoute,
  } as any)
const AuthenticatedNetworksVpcsIndexRoute =
  AuthenticatedNetworksVpcsIndexRouteImport.update({
    id: '/networks/vpcs/',
    path: '/networks/vpcs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksSubnetsIndexRoute =
  AuthenticatedNetworksSubnetsIndexRouteImport.update({
    id: '/networks/subnets/',
    path: '/networks/subnets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksSecurityGroupsIndexRoute =
  AuthenticatedNetworksSecurityGroupsIndexRouteImport.update({
    id: '/networks/security-groups/',
    path: '/networks/security-groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksRoutesIndexRoute =
  AuthenticatedNetworksRoutesIndexRouteImport.update({
    id: '/networks/routes/',
    path: '/networks/routes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksLoadBalancersIndexRoute =
  AuthenticatedNetworksLoadBalancersIndexRouteImport.update({
    id: '/networks/load-balancers/',
    path: '/networks/load-balancers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObjectsBucketIdObjectIdRoute =
  AuthenticatedObjectsBucketIdObjectIdRouteImport.update({
    id: '/$objectId',
    path: '/$objectId',
    getParentRoute: () => AuthenticatedObjectsBucketIdRoute,
  } as any)
const AuthenticatedNetworksVpcsVpcIdRoute =
  AuthenticatedNetworksVpcsVpcIdRouteImport.update({
    id: '/networks/vpcs/$vpcId',
    path: '/networks/vpcs/$vpcId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksSubnetsSubnetIdRoute =
  AuthenticatedNetworksSubnetsSubnetIdRouteImport.update({
    id: '/networks/subnets/$subnetId',
    path: '/networks/subnets/$subnetId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute =
  AuthenticatedNetworksSecurityGroupsSecurityGroupIdRouteImport.update({
    id: '/networks/security-groups/$securityGroupId',
    path: '/networks/security-groups/$securityGroupId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksRoutesRouteIdRoute =
  AuthenticatedNetworksRoutesRouteIdRouteImport.update({
    id: '/networks/routes/$routeId',
    path: '/networks/routes/$routeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute =
  AuthenticatedNetworksLoadBalancersLoadBalancerIdRouteImport.update({
    id: '/networks/load-balancers/$loadBalancerId',
    path: '/networks/load-balancers/$loadBalancerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesVmCreateRoute =
  AuthenticatedInstancesVmCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedInstancesVmRoute,
  } as any)
const AuthenticatedInstancesVmInstanceIdRoute =
  AuthenticatedInstancesVmInstanceIdRouteImport.update({
    id: '/$instanceId',
    path: '/$instanceId',
    getParentRoute: () => AuthenticatedInstancesVmRoute,
  } as any)
const AuthenticatedInstancesSandboxCreateRoute =
  AuthenticatedInstancesSandboxCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedInstancesSandboxRoute,
  } as any)
const AuthenticatedInstancesSandboxInstanceIdRoute =
  AuthenticatedInstancesSandboxInstanceIdRouteImport.update({
    id: '/$instanceId',
    path: '/$instanceId',
    getParentRoute: () => AuthenticatedInstancesSandboxRoute,
  } as any)
const AuthenticatedInstancesGpuCreateRoute =
  AuthenticatedInstancesGpuCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedInstancesGpuRoute,
  } as any)
const AuthenticatedInstancesContainerInstanceIdRoute =
  AuthenticatedInstancesContainerInstanceIdRouteImport.update({
    id: '/$instanceId',
    path: '/$instanceId',
    getParentRoute: () => AuthenticatedInstancesContainerRoute,
  } as any)
const AuthenticatedInstancesInstanceIdOperationsRoute =
  AuthenticatedInstancesInstanceIdOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedInstancesInstanceIdRoute,
  } as any)
const AuthenticatedInstancesContainerCreateRouteRoute =
  AuthenticatedInstancesContainerCreateRouteRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedInstancesContainerRoute,
  } as any)
const AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute =
  AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRouteImport.update({
    id: '/volumes/$volumeId',
    path: '/volumes/$volumeId',
    getParentRoute: () => AuthenticatedInstancesVmInstanceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteWithChildren
  '/login/callback': typeof LoginCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/demo/a-1': typeof AuthenticatedDemoA1Route
  '/demo/a-2': typeof AuthenticatedDemoA2Route
  '/demo/b-1': typeof AuthenticatedDemoB1Route
  '/demo/b-i-1': typeof AuthenticatedDemoBI1Route
  '/demo/b-i-2': typeof AuthenticatedDemoBI2Route
  '/demo/leaf': typeof AuthenticatedDemoLeafRoute
  '/filesystems/$filesystemId': typeof AuthenticatedFilesystemsFilesystemIdRoute
  '/instance-operations/$operationId': typeof AuthenticatedInstanceOperationsOperationIdRoute
  '/instances/$instanceId': typeof AuthenticatedInstancesInstanceIdRouteWithChildren
  '/instances/container': typeof AuthenticatedInstancesContainerRouteWithChildren
  '/instances/gpu': typeof AuthenticatedInstancesGpuRouteWithChildren
  '/instances/sandbox': typeof AuthenticatedInstancesSandboxRouteWithChildren
  '/instances/vm': typeof AuthenticatedInstancesVmRouteWithChildren
  '/k8s-clusters/$clusterId': typeof AuthenticatedK8sClustersClusterIdRoute
  '/objects/$bucketId': typeof AuthenticatedObjectsBucketIdRouteWithChildren
  '/secrets/$secretId': typeof AuthenticatedSecretsSecretIdRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/vector-stores/$vectorStoreId': typeof AuthenticatedVectorStoresVectorStoreIdRoute
  '/volumes/$volumeId': typeof AuthenticatedVolumesVolumeIdRoute
  '/instances/console/$instanceId': typeof InstancesConsoleInstanceIdRoute
  '/instances/terminal/$instanceId': typeof InstancesTerminalInstanceIdRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/bare-metal': typeof AuthenticatedBareMetalIndexRoute
  '/encryption': typeof AuthenticatedEncryptionIndexRoute
  '/filesystems': typeof AuthenticatedFilesystemsIndexRoute
  '/gpu-inventory': typeof AuthenticatedGpuInventoryIndexRoute
  '/images': typeof AuthenticatedImagesIndexRoute
  '/instances': typeof AuthenticatedInstancesIndexRoute
  '/k8s-clusters': typeof AuthenticatedK8sClustersIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/objects': typeof AuthenticatedObjectsIndexRoute
  '/observability': typeof AuthenticatedObservabilityIndexRoute
  '/registry': typeof AuthenticatedRegistryIndexRoute
  '/sandbox-templates': typeof AuthenticatedSandboxTemplatesIndexRoute
  '/secrets': typeof AuthenticatedSecretsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/usage': typeof AuthenticatedUsageIndexRoute
  '/vector-stores': typeof AuthenticatedVectorStoresIndexRoute
  '/volumes': typeof AuthenticatedVolumesIndexRoute
  '/instances/container/create': typeof AuthenticatedInstancesContainerCreateRouteRoute
  '/instances/$instanceId/operations': typeof AuthenticatedInstancesInstanceIdOperationsRoute
  '/instances/container/$instanceId': typeof AuthenticatedInstancesContainerInstanceIdRoute
  '/instances/gpu/create': typeof AuthenticatedInstancesGpuCreateRoute
  '/instances/sandbox/$instanceId': typeof AuthenticatedInstancesSandboxInstanceIdRoute
  '/instances/sandbox/create': typeof AuthenticatedInstancesSandboxCreateRoute
  '/instances/vm/$instanceId': typeof AuthenticatedInstancesVmInstanceIdRouteWithChildren
  '/instances/vm/create': typeof AuthenticatedInstancesVmCreateRoute
  '/networks/load-balancers/$loadBalancerId': typeof AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute
  '/networks/routes/$routeId': typeof AuthenticatedNetworksRoutesRouteIdRoute
  '/networks/security-groups/$securityGroupId': typeof AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute
  '/networks/subnets/$subnetId': typeof AuthenticatedNetworksSubnetsSubnetIdRoute
  '/networks/vpcs/$vpcId': typeof AuthenticatedNetworksVpcsVpcIdRoute
  '/objects/$bucketId/$objectId': typeof AuthenticatedObjectsBucketIdObjectIdRoute
  '/networks/load-balancers': typeof AuthenticatedNetworksLoadBalancersIndexRoute
  '/networks/routes': typeof AuthenticatedNetworksRoutesIndexRoute
  '/networks/security-groups': typeof AuthenticatedNetworksSecurityGroupsIndexRoute
  '/networks/subnets': typeof AuthenticatedNetworksSubnetsIndexRoute
  '/networks/vpcs': typeof AuthenticatedNetworksVpcsIndexRoute
  '/objects/$bucketId/': typeof AuthenticatedObjectsBucketIdIndexRoute
  '/instances/vm/$instanceId/volumes/$volumeId': typeof AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute
}
export interface FileRoutesByTo {
  '/login/callback': typeof LoginCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/demo/a-1': typeof AuthenticatedDemoA1Route
  '/demo/a-2': typeof AuthenticatedDemoA2Route
  '/demo/b-1': typeof AuthenticatedDemoB1Route
  '/demo/b-i-1': typeof AuthenticatedDemoBI1Route
  '/demo/b-i-2': typeof AuthenticatedDemoBI2Route
  '/demo/leaf': typeof AuthenticatedDemoLeafRoute
  '/filesystems/$filesystemId': typeof AuthenticatedFilesystemsFilesystemIdRoute
  '/instance-operations/$operationId': typeof AuthenticatedInstanceOperationsOperationIdRoute
  '/instances/$instanceId': typeof AuthenticatedInstancesInstanceIdRouteWithChildren
  '/instances/container': typeof AuthenticatedInstancesContainerRouteWithChildren
  '/instances/gpu': typeof AuthenticatedInstancesGpuRouteWithChildren
  '/instances/sandbox': typeof AuthenticatedInstancesSandboxRouteWithChildren
  '/instances/vm': typeof AuthenticatedInstancesVmRouteWithChildren
  '/k8s-clusters/$clusterId': typeof AuthenticatedK8sClustersClusterIdRoute
  '/secrets/$secretId': typeof AuthenticatedSecretsSecretIdRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/vector-stores/$vectorStoreId': typeof AuthenticatedVectorStoresVectorStoreIdRoute
  '/volumes/$volumeId': typeof AuthenticatedVolumesVolumeIdRoute
  '/instances/console/$instanceId': typeof InstancesConsoleInstanceIdRoute
  '/instances/terminal/$instanceId': typeof InstancesTerminalInstanceIdRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/bare-metal': typeof AuthenticatedBareMetalIndexRoute
  '/encryption': typeof AuthenticatedEncryptionIndexRoute
  '/filesystems': typeof AuthenticatedFilesystemsIndexRoute
  '/gpu-inventory': typeof AuthenticatedGpuInventoryIndexRoute
  '/images': typeof AuthenticatedImagesIndexRoute
  '/instances': typeof AuthenticatedInstancesIndexRoute
  '/k8s-clusters': typeof AuthenticatedK8sClustersIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/objects': typeof AuthenticatedObjectsIndexRoute
  '/observability': typeof AuthenticatedObservabilityIndexRoute
  '/registry': typeof AuthenticatedRegistryIndexRoute
  '/sandbox-templates': typeof AuthenticatedSandboxTemplatesIndexRoute
  '/secrets': typeof AuthenticatedSecretsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/usage': typeof AuthenticatedUsageIndexRoute
  '/vector-stores': typeof AuthenticatedVectorStoresIndexRoute
  '/volumes': typeof AuthenticatedVolumesIndexRoute
  '/instances/container/create': typeof AuthenticatedInstancesContainerCreateRouteRoute
  '/instances/$instanceId/operations': typeof AuthenticatedInstancesInstanceIdOperationsRoute
  '/instances/container/$instanceId': typeof AuthenticatedInstancesContainerInstanceIdRoute
  '/instances/gpu/create': typeof AuthenticatedInstancesGpuCreateRoute
  '/instances/sandbox/$instanceId': typeof AuthenticatedInstancesSandboxInstanceIdRoute
  '/instances/sandbox/create': typeof AuthenticatedInstancesSandboxCreateRoute
  '/instances/vm/$instanceId': typeof AuthenticatedInstancesVmInstanceIdRouteWithChildren
  '/instances/vm/create': typeof AuthenticatedInstancesVmCreateRoute
  '/networks/load-balancers/$loadBalancerId': typeof AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute
  '/networks/routes/$routeId': typeof AuthenticatedNetworksRoutesRouteIdRoute
  '/networks/security-groups/$securityGroupId': typeof AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute
  '/networks/subnets/$subnetId': typeof AuthenticatedNetworksSubnetsSubnetIdRoute
  '/networks/vpcs/$vpcId': typeof AuthenticatedNetworksVpcsVpcIdRoute
  '/objects/$bucketId/$objectId': typeof AuthenticatedObjectsBucketIdObjectIdRoute
  '/networks/load-balancers': typeof AuthenticatedNetworksLoadBalancersIndexRoute
  '/networks/routes': typeof AuthenticatedNetworksRoutesIndexRoute
  '/networks/security-groups': typeof AuthenticatedNetworksSecurityGroupsIndexRoute
  '/networks/subnets': typeof AuthenticatedNetworksSubnetsIndexRoute
  '/networks/vpcs': typeof AuthenticatedNetworksVpcsIndexRoute
  '/objects/$bucketId': typeof AuthenticatedObjectsBucketIdIndexRoute
  '/instances/vm/$instanceId/volumes/$volumeId': typeof AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/login/callback': typeof LoginCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/demo/a-1': typeof AuthenticatedDemoA1Route
  '/_authenticated/demo/a-2': typeof AuthenticatedDemoA2Route
  '/_authenticated/demo/b-1': typeof AuthenticatedDemoB1Route
  '/_authenticated/demo/b-i-1': typeof AuthenticatedDemoBI1Route
  '/_authenticated/demo/b-i-2': typeof AuthenticatedDemoBI2Route
  '/_authenticated/demo/leaf': typeof AuthenticatedDemoLeafRoute
  '/_authenticated/filesystems/$filesystemId': typeof AuthenticatedFilesystemsFilesystemIdRoute
  '/_authenticated/instance-operations/$operationId': typeof AuthenticatedInstanceOperationsOperationIdRoute
  '/_authenticated/instances/$instanceId': typeof AuthenticatedInstancesInstanceIdRouteWithChildren
  '/_authenticated/instances/container': typeof AuthenticatedInstancesContainerRouteWithChildren
  '/_authenticated/instances/gpu': typeof AuthenticatedInstancesGpuRouteWithChildren
  '/_authenticated/instances/sandbox': typeof AuthenticatedInstancesSandboxRouteWithChildren
  '/_authenticated/instances/vm': typeof AuthenticatedInstancesVmRouteWithChildren
  '/_authenticated/k8s-clusters/$clusterId': typeof AuthenticatedK8sClustersClusterIdRoute
  '/_authenticated/objects/$bucketId': typeof AuthenticatedObjectsBucketIdRouteWithChildren
  '/_authenticated/secrets/$secretId': typeof AuthenticatedSecretsSecretIdRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/vector-stores/$vectorStoreId': typeof AuthenticatedVectorStoresVectorStoreIdRoute
  '/_authenticated/volumes/$volumeId': typeof AuthenticatedVolumesVolumeIdRoute
  '/instances/console/$instanceId': typeof InstancesConsoleInstanceIdRoute
  '/instances/terminal/$instanceId': typeof InstancesTerminalInstanceIdRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/bare-metal/': typeof AuthenticatedBareMetalIndexRoute
  '/_authenticated/encryption/': typeof AuthenticatedEncryptionIndexRoute
  '/_authenticated/filesystems/': typeof AuthenticatedFilesystemsIndexRoute
  '/_authenticated/gpu-inventory/': typeof AuthenticatedGpuInventoryIndexRoute
  '/_authenticated/images/': typeof AuthenticatedImagesIndexRoute
  '/_authenticated/instances/': typeof AuthenticatedInstancesIndexRoute
  '/_authenticated/k8s-clusters/': typeof AuthenticatedK8sClustersIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/objects/': typeof AuthenticatedObjectsIndexRoute
  '/_authenticated/observability/': typeof AuthenticatedObservabilityIndexRoute
  '/_authenticated/registry/': typeof AuthenticatedRegistryIndexRoute
  '/_authenticated/sandbox-templates/': typeof AuthenticatedSandboxTemplatesIndexRoute
  '/_authenticated/secrets/': typeof AuthenticatedSecretsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/usage/': typeof AuthenticatedUsageIndexRoute
  '/_authenticated/vector-stores/': typeof AuthenticatedVectorStoresIndexRoute
  '/_authenticated/volumes/': typeof AuthenticatedVolumesIndexRoute
  '/_authenticated/instances/container/create': typeof AuthenticatedInstancesContainerCreateRouteRoute
  '/_authenticated/instances/$instanceId/operations': typeof AuthenticatedInstancesInstanceIdOperationsRoute
  '/_authenticated/instances/container/$instanceId': typeof AuthenticatedInstancesContainerInstanceIdRoute
  '/_authenticated/instances/gpu/create': typeof AuthenticatedInstancesGpuCreateRoute
  '/_authenticated/instances/sandbox/$instanceId': typeof AuthenticatedInstancesSandboxInstanceIdRoute
  '/_authenticated/instances/sandbox/create': typeof AuthenticatedInstancesSandboxCreateRoute
  '/_authenticated/instances/vm/$instanceId': typeof AuthenticatedInstancesVmInstanceIdRouteWithChildren
  '/_authenticated/instances/vm/create': typeof AuthenticatedInstancesVmCreateRoute
  '/_authenticated/networks/load-balancers/$loadBalancerId': typeof AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute
  '/_authenticated/networks/routes/$routeId': typeof AuthenticatedNetworksRoutesRouteIdRoute
  '/_authenticated/networks/security-groups/$securityGroupId': typeof AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute
  '/_authenticated/networks/subnets/$subnetId': typeof AuthenticatedNetworksSubnetsSubnetIdRoute
  '/_authenticated/networks/vpcs/$vpcId': typeof AuthenticatedNetworksVpcsVpcIdRoute
  '/_authenticated/objects/$bucketId/$objectId': typeof AuthenticatedObjectsBucketIdObjectIdRoute
  '/_authenticated/networks/load-balancers/': typeof AuthenticatedNetworksLoadBalancersIndexRoute
  '/_authenticated/networks/routes/': typeof AuthenticatedNetworksRoutesIndexRoute
  '/_authenticated/networks/security-groups/': typeof AuthenticatedNetworksSecurityGroupsIndexRoute
  '/_authenticated/networks/subnets/': typeof AuthenticatedNetworksSubnetsIndexRoute
  '/_authenticated/networks/vpcs/': typeof AuthenticatedNetworksVpcsIndexRoute
  '/_authenticated/objects/$bucketId/': typeof AuthenticatedObjectsBucketIdIndexRoute
  '/_authenticated/instances/vm/$instanceId/volumes/$volumeId': typeof AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/login/callback'
    | '/'
    | '/login/'
    | '/demo/a-1'
    | '/demo/a-2'
    | '/demo/b-1'
    | '/demo/b-i-1'
    | '/demo/b-i-2'
    | '/demo/leaf'
    | '/filesystems/$filesystemId'
    | '/instance-operations/$operationId'
    | '/instances/$instanceId'
    | '/instances/container'
    | '/instances/gpu'
    | '/instances/sandbox'
    | '/instances/vm'
    | '/k8s-clusters/$clusterId'
    | '/objects/$bucketId'
    | '/secrets/$secretId'
    | '/settings/api-keys'
    | '/vector-stores/$vectorStoreId'
    | '/volumes/$volumeId'
    | '/instances/console/$instanceId'
    | '/instances/terminal/$instanceId'
    | '/audit'
    | '/bare-metal'
    | '/encryption'
    | '/filesystems'
    | '/gpu-inventory'
    | '/images'
    | '/instances'
    | '/k8s-clusters'
    | '/notifications'
    | '/objects'
    | '/observability'
    | '/registry'
    | '/sandbox-templates'
    | '/secrets'
    | '/settings'
    | '/usage'
    | '/vector-stores'
    | '/volumes'
    | '/instances/container/create'
    | '/instances/$instanceId/operations'
    | '/instances/container/$instanceId'
    | '/instances/gpu/create'
    | '/instances/sandbox/$instanceId'
    | '/instances/sandbox/create'
    | '/instances/vm/$instanceId'
    | '/instances/vm/create'
    | '/networks/load-balancers/$loadBalancerId'
    | '/networks/routes/$routeId'
    | '/networks/security-groups/$securityGroupId'
    | '/networks/subnets/$subnetId'
    | '/networks/vpcs/$vpcId'
    | '/objects/$bucketId/$objectId'
    | '/networks/load-balancers'
    | '/networks/routes'
    | '/networks/security-groups'
    | '/networks/subnets'
    | '/networks/vpcs'
    | '/objects/$bucketId/'
    | '/instances/vm/$instanceId/volumes/$volumeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login/callback'
    | '/'
    | '/login'
    | '/demo/a-1'
    | '/demo/a-2'
    | '/demo/b-1'
    | '/demo/b-i-1'
    | '/demo/b-i-2'
    | '/demo/leaf'
    | '/filesystems/$filesystemId'
    | '/instance-operations/$operationId'
    | '/instances/$instanceId'
    | '/instances/container'
    | '/instances/gpu'
    | '/instances/sandbox'
    | '/instances/vm'
    | '/k8s-clusters/$clusterId'
    | '/secrets/$secretId'
    | '/settings/api-keys'
    | '/vector-stores/$vectorStoreId'
    | '/volumes/$volumeId'
    | '/instances/console/$instanceId'
    | '/instances/terminal/$instanceId'
    | '/audit'
    | '/bare-metal'
    | '/encryption'
    | '/filesystems'
    | '/gpu-inventory'
    | '/images'
    | '/instances'
    | '/k8s-clusters'
    | '/notifications'
    | '/objects'
    | '/observability'
    | '/registry'
    | '/sandbox-templates'
    | '/secrets'
    | '/settings'
    | '/usage'
    | '/vector-stores'
    | '/volumes'
    | '/instances/container/create'
    | '/instances/$instanceId/operations'
    | '/instances/container/$instanceId'
    | '/instances/gpu/create'
    | '/instances/sandbox/$instanceId'
    | '/instances/sandbox/create'
    | '/instances/vm/$instanceId'
    | '/instances/vm/create'
    | '/networks/load-balancers/$loadBalancerId'
    | '/networks/routes/$routeId'
    | '/networks/security-groups/$securityGroupId'
    | '/networks/subnets/$subnetId'
    | '/networks/vpcs/$vpcId'
    | '/objects/$bucketId/$objectId'
    | '/networks/load-balancers'
    | '/networks/routes'
    | '/networks/security-groups'
    | '/networks/subnets'
    | '/networks/vpcs'
    | '/objects/$bucketId'
    | '/instances/vm/$instanceId/volumes/$volumeId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/login/callback'
    | '/_authenticated/'
    | '/login/'
    | '/_authenticated/demo/a-1'
    | '/_authenticated/demo/a-2'
    | '/_authenticated/demo/b-1'
    | '/_authenticated/demo/b-i-1'
    | '/_authenticated/demo/b-i-2'
    | '/_authenticated/demo/leaf'
    | '/_authenticated/filesystems/$filesystemId'
    | '/_authenticated/instance-operations/$operationId'
    | '/_authenticated/instances/$instanceId'
    | '/_authenticated/instances/container'
    | '/_authenticated/instances/gpu'
    | '/_authenticated/instances/sandbox'
    | '/_authenticated/instances/vm'
    | '/_authenticated/k8s-clusters/$clusterId'
    | '/_authenticated/objects/$bucketId'
    | '/_authenticated/secrets/$secretId'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/vector-stores/$vectorStoreId'
    | '/_authenticated/volumes/$volumeId'
    | '/instances/console/$instanceId'
    | '/instances/terminal/$instanceId'
    | '/_authenticated/audit/'
    | '/_authenticated/bare-metal/'
    | '/_authenticated/encryption/'
    | '/_authenticated/filesystems/'
    | '/_authenticated/gpu-inventory/'
    | '/_authenticated/images/'
    | '/_authenticated/instances/'
    | '/_authenticated/k8s-clusters/'
    | '/_authenticated/notifications/'
    | '/_authenticated/objects/'
    | '/_authenticated/observability/'
    | '/_authenticated/registry/'
    | '/_authenticated/sandbox-templates/'
    | '/_authenticated/secrets/'
    | '/_authenticated/settings/'
    | '/_authenticated/usage/'
    | '/_authenticated/vector-stores/'
    | '/_authenticated/volumes/'
    | '/_authenticated/instances/container/create'
    | '/_authenticated/instances/$instanceId/operations'
    | '/_authenticated/instances/container/$instanceId'
    | '/_authenticated/instances/gpu/create'
    | '/_authenticated/instances/sandbox/$instanceId'
    | '/_authenticated/instances/sandbox/create'
    | '/_authenticated/instances/vm/$instanceId'
    | '/_authenticated/instances/vm/create'
    | '/_authenticated/networks/load-balancers/$loadBalancerId'
    | '/_authenticated/networks/routes/$routeId'
    | '/_authenticated/networks/security-groups/$securityGroupId'
    | '/_authenticated/networks/subnets/$subnetId'
    | '/_authenticated/networks/vpcs/$vpcId'
    | '/_authenticated/objects/$bucketId/$objectId'
    | '/_authenticated/networks/load-balancers/'
    | '/_authenticated/networks/routes/'
    | '/_authenticated/networks/security-groups/'
    | '/_authenticated/networks/subnets/'
    | '/_authenticated/networks/vpcs/'
    | '/_authenticated/objects/$bucketId/'
    | '/_authenticated/instances/vm/$instanceId/volumes/$volumeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  InstancesConsoleInstanceIdRoute: typeof InstancesConsoleInstanceIdRoute
  InstancesTerminalInstanceIdRoute: typeof InstancesTerminalInstanceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/volumes/': {
      id: '/_authenticated/volumes/'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof AuthenticatedVolumesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vector-stores/': {
      id: '/_authenticated/vector-stores/'
      path: '/vector-stores'
      fullPath: '/vector-stores'
      preLoaderRoute: typeof AuthenticatedVectorStoresIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usage/': {
      id: '/_authenticated/usage/'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secrets/': {
      id: '/_authenticated/secrets/'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof AuthenticatedSecretsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandbox-templates/': {
      id: '/_authenticated/sandbox-templates/'
      path: '/sandbox-templates'
      fullPath: '/sandbox-templates'
      preLoaderRoute: typeof AuthenticatedSandboxTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registry/': {
      id: '/_authenticated/registry/'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof AuthenticatedRegistryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/observability/': {
      id: '/_authenticated/observability/'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof AuthenticatedObservabilityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objects/': {
      id: '/_authenticated/objects/'
      path: '/objects'
      fullPath: '/objects'
      preLoaderRoute: typeof AuthenticatedObjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/k8s-clusters/': {
      id: '/_authenticated/k8s-clusters/'
      path: '/k8s-clusters'
      fullPath: '/k8s-clusters'
      preLoaderRoute: typeof AuthenticatedK8sClustersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/': {
      id: '/_authenticated/instances/'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof AuthenticatedInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/images/': {
      id: '/_authenticated/images/'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AuthenticatedImagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gpu-inventory/': {
      id: '/_authenticated/gpu-inventory/'
      path: '/gpu-inventory'
      fullPath: '/gpu-inventory'
      preLoaderRoute: typeof AuthenticatedGpuInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/filesystems/': {
      id: '/_authenticated/filesystems/'
      path: '/filesystems'
      fullPath: '/filesystems'
      preLoaderRoute: typeof AuthenticatedFilesystemsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/encryption/': {
      id: '/_authenticated/encryption/'
      path: '/encryption'
      fullPath: '/encryption'
      preLoaderRoute: typeof AuthenticatedEncryptionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bare-metal/': {
      id: '/_authenticated/bare-metal/'
      path: '/bare-metal'
      fullPath: '/bare-metal'
      preLoaderRoute: typeof AuthenticatedBareMetalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/instances/terminal/$instanceId': {
      id: '/instances/terminal/$instanceId'
      path: '/instances/terminal/$instanceId'
      fullPath: '/instances/terminal/$instanceId'
      preLoaderRoute: typeof InstancesTerminalInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/console/$instanceId': {
      id: '/instances/console/$instanceId'
      path: '/instances/console/$instanceId'
      fullPath: '/instances/console/$instanceId'
      preLoaderRoute: typeof InstancesConsoleInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/volumes/$volumeId': {
      id: '/_authenticated/volumes/$volumeId'
      path: '/volumes/$volumeId'
      fullPath: '/volumes/$volumeId'
      preLoaderRoute: typeof AuthenticatedVolumesVolumeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vector-stores/$vectorStoreId': {
      id: '/_authenticated/vector-stores/$vectorStoreId'
      path: '/vector-stores/$vectorStoreId'
      fullPath: '/vector-stores/$vectorStoreId'
      preLoaderRoute: typeof AuthenticatedVectorStoresVectorStoreIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secrets/$secretId': {
      id: '/_authenticated/secrets/$secretId'
      path: '/secrets/$secretId'
      fullPath: '/secrets/$secretId'
      preLoaderRoute: typeof AuthenticatedSecretsSecretIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objects/$bucketId': {
      id: '/_authenticated/objects/$bucketId'
      path: '/objects/$bucketId'
      fullPath: '/objects/$bucketId'
      preLoaderRoute: typeof AuthenticatedObjectsBucketIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/k8s-clusters/$clusterId': {
      id: '/_authenticated/k8s-clusters/$clusterId'
      path: '/k8s-clusters/$clusterId'
      fullPath: '/k8s-clusters/$clusterId'
      preLoaderRoute: typeof AuthenticatedK8sClustersClusterIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/vm': {
      id: '/_authenticated/instances/vm'
      path: '/instances/vm'
      fullPath: '/instances/vm'
      preLoaderRoute: typeof AuthenticatedInstancesVmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/sandbox': {
      id: '/_authenticated/instances/sandbox'
      path: '/instances/sandbox'
      fullPath: '/instances/sandbox'
      preLoaderRoute: typeof AuthenticatedInstancesSandboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/gpu': {
      id: '/_authenticated/instances/gpu'
      path: '/instances/gpu'
      fullPath: '/instances/gpu'
      preLoaderRoute: typeof AuthenticatedInstancesGpuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/container': {
      id: '/_authenticated/instances/container'
      path: '/instances/container'
      fullPath: '/instances/container'
      preLoaderRoute: typeof AuthenticatedInstancesContainerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/$instanceId': {
      id: '/_authenticated/instances/$instanceId'
      path: '/instances/$instanceId'
      fullPath: '/instances/$instanceId'
      preLoaderRoute: typeof AuthenticatedInstancesInstanceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instance-operations/$operationId': {
      id: '/_authenticated/instance-operations/$operationId'
      path: '/instance-operations/$operationId'
      fullPath: '/instance-operations/$operationId'
      preLoaderRoute: typeof AuthenticatedInstanceOperationsOperationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/filesystems/$filesystemId': {
      id: '/_authenticated/filesystems/$filesystemId'
      path: '/filesystems/$filesystemId'
      fullPath: '/filesystems/$filesystemId'
      preLoaderRoute: typeof AuthenticatedFilesystemsFilesystemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/leaf': {
      id: '/_authenticated/demo/leaf'
      path: '/demo/leaf'
      fullPath: '/demo/leaf'
      preLoaderRoute: typeof AuthenticatedDemoLeafRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/b-i-2': {
      id: '/_authenticated/demo/b-i-2'
      path: '/demo/b-i-2'
      fullPath: '/demo/b-i-2'
      preLoaderRoute: typeof AuthenticatedDemoBI2RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/b-i-1': {
      id: '/_authenticated/demo/b-i-1'
      path: '/demo/b-i-1'
      fullPath: '/demo/b-i-1'
      preLoaderRoute: typeof AuthenticatedDemoBI1RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/b-1': {
      id: '/_authenticated/demo/b-1'
      path: '/demo/b-1'
      fullPath: '/demo/b-1'
      preLoaderRoute: typeof AuthenticatedDemoB1RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/a-2': {
      id: '/_authenticated/demo/a-2'
      path: '/demo/a-2'
      fullPath: '/demo/a-2'
      preLoaderRoute: typeof AuthenticatedDemoA2RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/a-1': {
      id: '/_authenticated/demo/a-1'
      path: '/demo/a-1'
      fullPath: '/demo/a-1'
      preLoaderRoute: typeof AuthenticatedDemoA1RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objects/$bucketId/': {
      id: '/_authenticated/objects/$bucketId/'
      path: '/'
      fullPath: '/objects/$bucketId/'
      preLoaderRoute: typeof AuthenticatedObjectsBucketIdIndexRouteImport
      parentRoute: typeof AuthenticatedObjectsBucketIdRoute
    }
    '/_authenticated/networks/vpcs/': {
      id: '/_authenticated/networks/vpcs/'
      path: '/networks/vpcs'
      fullPath: '/networks/vpcs'
      preLoaderRoute: typeof AuthenticatedNetworksVpcsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/subnets/': {
      id: '/_authenticated/networks/subnets/'
      path: '/networks/subnets'
      fullPath: '/networks/subnets'
      preLoaderRoute: typeof AuthenticatedNetworksSubnetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/security-groups/': {
      id: '/_authenticated/networks/security-groups/'
      path: '/networks/security-groups'
      fullPath: '/networks/security-groups'
      preLoaderRoute: typeof AuthenticatedNetworksSecurityGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/routes/': {
      id: '/_authenticated/networks/routes/'
      path: '/networks/routes'
      fullPath: '/networks/routes'
      preLoaderRoute: typeof AuthenticatedNetworksRoutesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/load-balancers/': {
      id: '/_authenticated/networks/load-balancers/'
      path: '/networks/load-balancers'
      fullPath: '/networks/load-balancers'
      preLoaderRoute: typeof AuthenticatedNetworksLoadBalancersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objects/$bucketId/$objectId': {
      id: '/_authenticated/objects/$bucketId/$objectId'
      path: '/$objectId'
      fullPath: '/objects/$bucketId/$objectId'
      preLoaderRoute: typeof AuthenticatedObjectsBucketIdObjectIdRouteImport
      parentRoute: typeof AuthenticatedObjectsBucketIdRoute
    }
    '/_authenticated/networks/vpcs/$vpcId': {
      id: '/_authenticated/networks/vpcs/$vpcId'
      path: '/networks/vpcs/$vpcId'
      fullPath: '/networks/vpcs/$vpcId'
      preLoaderRoute: typeof AuthenticatedNetworksVpcsVpcIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/subnets/$subnetId': {
      id: '/_authenticated/networks/subnets/$subnetId'
      path: '/networks/subnets/$subnetId'
      fullPath: '/networks/subnets/$subnetId'
      preLoaderRoute: typeof AuthenticatedNetworksSubnetsSubnetIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/security-groups/$securityGroupId': {
      id: '/_authenticated/networks/security-groups/$securityGroupId'
      path: '/networks/security-groups/$securityGroupId'
      fullPath: '/networks/security-groups/$securityGroupId'
      preLoaderRoute: typeof AuthenticatedNetworksSecurityGroupsSecurityGroupIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/routes/$routeId': {
      id: '/_authenticated/networks/routes/$routeId'
      path: '/networks/routes/$routeId'
      fullPath: '/networks/routes/$routeId'
      preLoaderRoute: typeof AuthenticatedNetworksRoutesRouteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/load-balancers/$loadBalancerId': {
      id: '/_authenticated/networks/load-balancers/$loadBalancerId'
      path: '/networks/load-balancers/$loadBalancerId'
      fullPath: '/networks/load-balancers/$loadBalancerId'
      preLoaderRoute: typeof AuthenticatedNetworksLoadBalancersLoadBalancerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/vm/create': {
      id: '/_authenticated/instances/vm/create'
      path: '/create'
      fullPath: '/instances/vm/create'
      preLoaderRoute: typeof AuthenticatedInstancesVmCreateRouteImport
      parentRoute: typeof AuthenticatedInstancesVmRoute
    }
    '/_authenticated/instances/vm/$instanceId': {
      id: '/_authenticated/instances/vm/$instanceId'
      path: '/$instanceId'
      fullPath: '/instances/vm/$instanceId'
      preLoaderRoute: typeof AuthenticatedInstancesVmInstanceIdRouteImport
      parentRoute: typeof AuthenticatedInstancesVmRoute
    }
    '/_authenticated/instances/sandbox/create': {
      id: '/_authenticated/instances/sandbox/create'
      path: '/create'
      fullPath: '/instances/sandbox/create'
      preLoaderRoute: typeof AuthenticatedInstancesSandboxCreateRouteImport
      parentRoute: typeof AuthenticatedInstancesSandboxRoute
    }
    '/_authenticated/instances/sandbox/$instanceId': {
      id: '/_authenticated/instances/sandbox/$instanceId'
      path: '/$instanceId'
      fullPath: '/instances/sandbox/$instanceId'
      preLoaderRoute: typeof AuthenticatedInstancesSandboxInstanceIdRouteImport
      parentRoute: typeof AuthenticatedInstancesSandboxRoute
    }
    '/_authenticated/instances/gpu/create': {
      id: '/_authenticated/instances/gpu/create'
      path: '/create'
      fullPath: '/instances/gpu/create'
      preLoaderRoute: typeof AuthenticatedInstancesGpuCreateRouteImport
      parentRoute: typeof AuthenticatedInstancesGpuRoute
    }
    '/_authenticated/instances/container/$instanceId': {
      id: '/_authenticated/instances/container/$instanceId'
      path: '/$instanceId'
      fullPath: '/instances/container/$instanceId'
      preLoaderRoute: typeof AuthenticatedInstancesContainerInstanceIdRouteImport
      parentRoute: typeof AuthenticatedInstancesContainerRoute
    }
    '/_authenticated/instances/$instanceId/operations': {
      id: '/_authenticated/instances/$instanceId/operations'
      path: '/operations'
      fullPath: '/instances/$instanceId/operations'
      preLoaderRoute: typeof AuthenticatedInstancesInstanceIdOperationsRouteImport
      parentRoute: typeof AuthenticatedInstancesInstanceIdRoute
    }
    '/_authenticated/instances/container/create': {
      id: '/_authenticated/instances/container/create'
      path: '/create'
      fullPath: '/instances/container/create'
      preLoaderRoute: typeof AuthenticatedInstancesContainerCreateRouteRouteImport
      parentRoute: typeof AuthenticatedInstancesContainerRoute
    }
    '/_authenticated/instances/vm/$instanceId/volumes/$volumeId': {
      id: '/_authenticated/instances/vm/$instanceId/volumes/$volumeId'
      path: '/volumes/$volumeId'
      fullPath: '/instances/vm/$instanceId/volumes/$volumeId'
      preLoaderRoute: typeof AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRouteImport
      parentRoute: typeof AuthenticatedInstancesVmInstanceIdRoute
    }
  }
}

interface AuthenticatedInstancesInstanceIdRouteChildren {
  AuthenticatedInstancesInstanceIdOperationsRoute: typeof AuthenticatedInstancesInstanceIdOperationsRoute
}

const AuthenticatedInstancesInstanceIdRouteChildren: AuthenticatedInstancesInstanceIdRouteChildren =
  {
    AuthenticatedInstancesInstanceIdOperationsRoute:
      AuthenticatedInstancesInstanceIdOperationsRoute,
  }

const AuthenticatedInstancesInstanceIdRouteWithChildren =
  AuthenticatedInstancesInstanceIdRoute._addFileChildren(
    AuthenticatedInstancesInstanceIdRouteChildren,
  )

interface AuthenticatedInstancesContainerRouteChildren {
  AuthenticatedInstancesContainerCreateRouteRoute: typeof AuthenticatedInstancesContainerCreateRouteRoute
  AuthenticatedInstancesContainerInstanceIdRoute: typeof AuthenticatedInstancesContainerInstanceIdRoute
}

const AuthenticatedInstancesContainerRouteChildren: AuthenticatedInstancesContainerRouteChildren =
  {
    AuthenticatedInstancesContainerCreateRouteRoute:
      AuthenticatedInstancesContainerCreateRouteRoute,
    AuthenticatedInstancesContainerInstanceIdRoute:
      AuthenticatedInstancesContainerInstanceIdRoute,
  }

const AuthenticatedInstancesContainerRouteWithChildren =
  AuthenticatedInstancesContainerRoute._addFileChildren(
    AuthenticatedInstancesContainerRouteChildren,
  )

interface AuthenticatedInstancesGpuRouteChildren {
  AuthenticatedInstancesGpuCreateRoute: typeof AuthenticatedInstancesGpuCreateRoute
}

const AuthenticatedInstancesGpuRouteChildren: AuthenticatedInstancesGpuRouteChildren =
  {
    AuthenticatedInstancesGpuCreateRoute: AuthenticatedInstancesGpuCreateRoute,
  }

const AuthenticatedInstancesGpuRouteWithChildren =
  AuthenticatedInstancesGpuRoute._addFileChildren(
    AuthenticatedInstancesGpuRouteChildren,
  )

interface AuthenticatedInstancesSandboxRouteChildren {
  AuthenticatedInstancesSandboxInstanceIdRoute: typeof AuthenticatedInstancesSandboxInstanceIdRoute
  AuthenticatedInstancesSandboxCreateRoute: typeof AuthenticatedInstancesSandboxCreateRoute
}

const AuthenticatedInstancesSandboxRouteChildren: AuthenticatedInstancesSandboxRouteChildren =
  {
    AuthenticatedInstancesSandboxInstanceIdRoute:
      AuthenticatedInstancesSandboxInstanceIdRoute,
    AuthenticatedInstancesSandboxCreateRoute:
      AuthenticatedInstancesSandboxCreateRoute,
  }

const AuthenticatedInstancesSandboxRouteWithChildren =
  AuthenticatedInstancesSandboxRoute._addFileChildren(
    AuthenticatedInstancesSandboxRouteChildren,
  )

interface AuthenticatedInstancesVmInstanceIdRouteChildren {
  AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute: typeof AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute
}

const AuthenticatedInstancesVmInstanceIdRouteChildren: AuthenticatedInstancesVmInstanceIdRouteChildren =
  {
    AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute:
      AuthenticatedInstancesVmInstanceIdVolumesVolumeIdRoute,
  }

const AuthenticatedInstancesVmInstanceIdRouteWithChildren =
  AuthenticatedInstancesVmInstanceIdRoute._addFileChildren(
    AuthenticatedInstancesVmInstanceIdRouteChildren,
  )

interface AuthenticatedInstancesVmRouteChildren {
  AuthenticatedInstancesVmInstanceIdRoute: typeof AuthenticatedInstancesVmInstanceIdRouteWithChildren
  AuthenticatedInstancesVmCreateRoute: typeof AuthenticatedInstancesVmCreateRoute
}

const AuthenticatedInstancesVmRouteChildren: AuthenticatedInstancesVmRouteChildren =
  {
    AuthenticatedInstancesVmInstanceIdRoute:
      AuthenticatedInstancesVmInstanceIdRouteWithChildren,
    AuthenticatedInstancesVmCreateRoute: AuthenticatedInstancesVmCreateRoute,
  }

const AuthenticatedInstancesVmRouteWithChildren =
  AuthenticatedInstancesVmRoute._addFileChildren(
    AuthenticatedInstancesVmRouteChildren,
  )

interface AuthenticatedObjectsBucketIdRouteChildren {
  AuthenticatedObjectsBucketIdObjectIdRoute: typeof AuthenticatedObjectsBucketIdObjectIdRoute
  AuthenticatedObjectsBucketIdIndexRoute: typeof AuthenticatedObjectsBucketIdIndexRoute
}

const AuthenticatedObjectsBucketIdRouteChildren: AuthenticatedObjectsBucketIdRouteChildren =
  {
    AuthenticatedObjectsBucketIdObjectIdRoute:
      AuthenticatedObjectsBucketIdObjectIdRoute,
    AuthenticatedObjectsBucketIdIndexRoute:
      AuthenticatedObjectsBucketIdIndexRoute,
  }

const AuthenticatedObjectsBucketIdRouteWithChildren =
  AuthenticatedObjectsBucketIdRoute._addFileChildren(
    AuthenticatedObjectsBucketIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDemoA1Route: typeof AuthenticatedDemoA1Route
  AuthenticatedDemoA2Route: typeof AuthenticatedDemoA2Route
  AuthenticatedDemoB1Route: typeof AuthenticatedDemoB1Route
  AuthenticatedDemoBI1Route: typeof AuthenticatedDemoBI1Route
  AuthenticatedDemoBI2Route: typeof AuthenticatedDemoBI2Route
  AuthenticatedDemoLeafRoute: typeof AuthenticatedDemoLeafRoute
  AuthenticatedFilesystemsFilesystemIdRoute: typeof AuthenticatedFilesystemsFilesystemIdRoute
  AuthenticatedInstanceOperationsOperationIdRoute: typeof AuthenticatedInstanceOperationsOperationIdRoute
  AuthenticatedInstancesInstanceIdRoute: typeof AuthenticatedInstancesInstanceIdRouteWithChildren
  AuthenticatedInstancesContainerRoute: typeof AuthenticatedInstancesContainerRouteWithChildren
  AuthenticatedInstancesGpuRoute: typeof AuthenticatedInstancesGpuRouteWithChildren
  AuthenticatedInstancesSandboxRoute: typeof AuthenticatedInstancesSandboxRouteWithChildren
  AuthenticatedInstancesVmRoute: typeof AuthenticatedInstancesVmRouteWithChildren
  AuthenticatedK8sClustersClusterIdRoute: typeof AuthenticatedK8sClustersClusterIdRoute
  AuthenticatedObjectsBucketIdRoute: typeof AuthenticatedObjectsBucketIdRouteWithChildren
  AuthenticatedSecretsSecretIdRoute: typeof AuthenticatedSecretsSecretIdRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedVectorStoresVectorStoreIdRoute: typeof AuthenticatedVectorStoresVectorStoreIdRoute
  AuthenticatedVolumesVolumeIdRoute: typeof AuthenticatedVolumesVolumeIdRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedBareMetalIndexRoute: typeof AuthenticatedBareMetalIndexRoute
  AuthenticatedEncryptionIndexRoute: typeof AuthenticatedEncryptionIndexRoute
  AuthenticatedFilesystemsIndexRoute: typeof AuthenticatedFilesystemsIndexRoute
  AuthenticatedGpuInventoryIndexRoute: typeof AuthenticatedGpuInventoryIndexRoute
  AuthenticatedImagesIndexRoute: typeof AuthenticatedImagesIndexRoute
  AuthenticatedInstancesIndexRoute: typeof AuthenticatedInstancesIndexRoute
  AuthenticatedK8sClustersIndexRoute: typeof AuthenticatedK8sClustersIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedObjectsIndexRoute: typeof AuthenticatedObjectsIndexRoute
  AuthenticatedObservabilityIndexRoute: typeof AuthenticatedObservabilityIndexRoute
  AuthenticatedRegistryIndexRoute: typeof AuthenticatedRegistryIndexRoute
  AuthenticatedSandboxTemplatesIndexRoute: typeof AuthenticatedSandboxTemplatesIndexRoute
  AuthenticatedSecretsIndexRoute: typeof AuthenticatedSecretsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedUsageIndexRoute: typeof AuthenticatedUsageIndexRoute
  AuthenticatedVectorStoresIndexRoute: typeof AuthenticatedVectorStoresIndexRoute
  AuthenticatedVolumesIndexRoute: typeof AuthenticatedVolumesIndexRoute
  AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute: typeof AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute
  AuthenticatedNetworksRoutesRouteIdRoute: typeof AuthenticatedNetworksRoutesRouteIdRoute
  AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute: typeof AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute
  AuthenticatedNetworksSubnetsSubnetIdRoute: typeof AuthenticatedNetworksSubnetsSubnetIdRoute
  AuthenticatedNetworksVpcsVpcIdRoute: typeof AuthenticatedNetworksVpcsVpcIdRoute
  AuthenticatedNetworksLoadBalancersIndexRoute: typeof AuthenticatedNetworksLoadBalancersIndexRoute
  AuthenticatedNetworksRoutesIndexRoute: typeof AuthenticatedNetworksRoutesIndexRoute
  AuthenticatedNetworksSecurityGroupsIndexRoute: typeof AuthenticatedNetworksSecurityGroupsIndexRoute
  AuthenticatedNetworksSubnetsIndexRoute: typeof AuthenticatedNetworksSubnetsIndexRoute
  AuthenticatedNetworksVpcsIndexRoute: typeof AuthenticatedNetworksVpcsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDemoA1Route: AuthenticatedDemoA1Route,
  AuthenticatedDemoA2Route: AuthenticatedDemoA2Route,
  AuthenticatedDemoB1Route: AuthenticatedDemoB1Route,
  AuthenticatedDemoBI1Route: AuthenticatedDemoBI1Route,
  AuthenticatedDemoBI2Route: AuthenticatedDemoBI2Route,
  AuthenticatedDemoLeafRoute: AuthenticatedDemoLeafRoute,
  AuthenticatedFilesystemsFilesystemIdRoute:
    AuthenticatedFilesystemsFilesystemIdRoute,
  AuthenticatedInstanceOperationsOperationIdRoute:
    AuthenticatedInstanceOperationsOperationIdRoute,
  AuthenticatedInstancesInstanceIdRoute:
    AuthenticatedInstancesInstanceIdRouteWithChildren,
  AuthenticatedInstancesContainerRoute:
    AuthenticatedInstancesContainerRouteWithChildren,
  AuthenticatedInstancesGpuRoute: AuthenticatedInstancesGpuRouteWithChildren,
  AuthenticatedInstancesSandboxRoute:
    AuthenticatedInstancesSandboxRouteWithChildren,
  AuthenticatedInstancesVmRoute: AuthenticatedInstancesVmRouteWithChildren,
  AuthenticatedK8sClustersClusterIdRoute:
    AuthenticatedK8sClustersClusterIdRoute,
  AuthenticatedObjectsBucketIdRoute:
    AuthenticatedObjectsBucketIdRouteWithChildren,
  AuthenticatedSecretsSecretIdRoute: AuthenticatedSecretsSecretIdRoute,
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
  AuthenticatedVectorStoresVectorStoreIdRoute:
    AuthenticatedVectorStoresVectorStoreIdRoute,
  AuthenticatedVolumesVolumeIdRoute: AuthenticatedVolumesVolumeIdRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedBareMetalIndexRoute: AuthenticatedBareMetalIndexRoute,
  AuthenticatedEncryptionIndexRoute: AuthenticatedEncryptionIndexRoute,
  AuthenticatedFilesystemsIndexRoute: AuthenticatedFilesystemsIndexRoute,
  AuthenticatedGpuInventoryIndexRoute: AuthenticatedGpuInventoryIndexRoute,
  AuthenticatedImagesIndexRoute: AuthenticatedImagesIndexRoute,
  AuthenticatedInstancesIndexRoute: AuthenticatedInstancesIndexRoute,
  AuthenticatedK8sClustersIndexRoute: AuthenticatedK8sClustersIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedObjectsIndexRoute: AuthenticatedObjectsIndexRoute,
  AuthenticatedObservabilityIndexRoute: AuthenticatedObservabilityIndexRoute,
  AuthenticatedRegistryIndexRoute: AuthenticatedRegistryIndexRoute,
  AuthenticatedSandboxTemplatesIndexRoute:
    AuthenticatedSandboxTemplatesIndexRoute,
  AuthenticatedSecretsIndexRoute: AuthenticatedSecretsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedUsageIndexRoute: AuthenticatedUsageIndexRoute,
  AuthenticatedVectorStoresIndexRoute: AuthenticatedVectorStoresIndexRoute,
  AuthenticatedVolumesIndexRoute: AuthenticatedVolumesIndexRoute,
  AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute:
    AuthenticatedNetworksLoadBalancersLoadBalancerIdRoute,
  AuthenticatedNetworksRoutesRouteIdRoute:
    AuthenticatedNetworksRoutesRouteIdRoute,
  AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute:
    AuthenticatedNetworksSecurityGroupsSecurityGroupIdRoute,
  AuthenticatedNetworksSubnetsSubnetIdRoute:
    AuthenticatedNetworksSubnetsSubnetIdRoute,
  AuthenticatedNetworksVpcsVpcIdRoute: AuthenticatedNetworksVpcsVpcIdRoute,
  AuthenticatedNetworksLoadBalancersIndexRoute:
    AuthenticatedNetworksLoadBalancersIndexRoute,
  AuthenticatedNetworksRoutesIndexRoute: AuthenticatedNetworksRoutesIndexRoute,
  AuthenticatedNetworksSecurityGroupsIndexRoute:
    AuthenticatedNetworksSecurityGroupsIndexRoute,
  AuthenticatedNetworksSubnetsIndexRoute:
    AuthenticatedNetworksSubnetsIndexRoute,
  AuthenticatedNetworksVpcsIndexRoute: AuthenticatedNetworksVpcsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginCallbackRoute: typeof LoginCallbackRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginCallbackRoute: LoginCallbackRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  InstancesConsoleInstanceIdRoute: InstancesConsoleInstanceIdRoute,
  InstancesTerminalInstanceIdRoute: InstancesTerminalInstanceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
